using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using MCPhappey.Core.Extensions;
using Microsoft.Extensions.DependencyInjection;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;

namespace MCPhappey.Tools.AgentMail;

public static class AgentMailInboxes
{
    [Description("Create an AgentMail inbox. Inputs are confirmed via elicitation before the POST request is sent.")]
    [McpServerTool(Title = "AgentMail create inbox", Name = "agentmail_inboxes_create", Destructive = false, OpenWorld = true)]
    public static async Task<CallToolResult?> AgentMail_Inboxes_Create(
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Optional username of the address. Randomly generated by AgentMail when omitted.")] string? username = null,
        [Description("Optional domain of the address. Must be a verified domain. Defaults to agentmail.to when omitted.")] string? domain = null,
        [Description("Optional display name, for example Display Name <username@domain.com>.")] string? displayName = null,
        [Description("Optional client-provided inbox idempotency/reference id.")] string? clientId = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
            await requestContext.WithStructuredContent(async () =>
            {
                var (typed, _, _) = await requestContext.Server.TryElicit(new AgentMailCreateInboxRequest
                {
                    Username = username,
                    Domain = domain,
                    DisplayName = displayName,
                    ClientId = clientId
                }, cancellationToken);

                var client = serviceProvider.GetRequiredService<AgentMailClient>();
                var response = await client.PostAsync("/v0/inboxes", BuildCreateInboxBody(typed), cancellationToken);
                return response.StructuredOrStatus("create inbox");
            }));

    [Description("Update an AgentMail inbox display name. Inputs are confirmed via elicitation before the PATCH request is sent.")]
    [McpServerTool(Title = "AgentMail update inbox", Name = "agentmail_inboxes_update", Destructive = false, OpenWorld = true)]
    public static async Task<CallToolResult?> AgentMail_Inboxes_Update(
        [Description("Inbox ID to update.")] string inboxId,
        [Description("New display name, for example Display Name <username@domain.com>.")] string displayName,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
            await requestContext.WithStructuredContent(async () =>
            {
                var (typed, _, _) = await requestContext.Server.TryElicit(new AgentMailUpdateInboxRequest
                {
                    InboxId = inboxId,
                    DisplayName = displayName
                }, cancellationToken);

                AgentMailHelpers.Require(typed.InboxId, nameof(inboxId));
                AgentMailHelpers.Require(typed.DisplayName, nameof(displayName));

                var client = serviceProvider.GetRequiredService<AgentMailClient>();
                var response = await client.PatchAsync($"/v0/inboxes/{AgentMailHelpers.EscapePath(typed.InboxId)}", new JsonObject
                {
                    ["display_name"] = typed.DisplayName
                }, cancellationToken);
                return response.StructuredOrStatus("update inbox");
            }));

    [Description("Delete an AgentMail inbox after explicit confirmation using the shared delete confirmation helper.")]
    [McpServerTool(Title = "AgentMail delete inbox", Name = "agentmail_inboxes_delete", Destructive = true, OpenWorld = true)]
    public static async Task<CallToolResult?> AgentMail_Inboxes_Delete(
        [Description("Inbox ID to delete.")] string inboxId,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
        {
            AgentMailHelpers.Require(inboxId, nameof(inboxId));
            var client = serviceProvider.GetRequiredService<AgentMailClient>();
            return await requestContext.ConfirmAndDeleteAsync<ConfirmDeleteAgentMailInbox>(
                inboxId,
                async ct => _ = await client.DeleteAsync($"/v0/inboxes/{AgentMailHelpers.EscapePath(inboxId)}", ct),
                $"AgentMail inbox '{inboxId}' deleted successfully.",
                cancellationToken);
        });

    [Description("Create an AgentMail inbox inside a pod. Inputs are confirmed via elicitation before the POST request is sent.")]
    [McpServerTool(Title = "AgentMail create pod inbox", Name = "agentmail_pods_inboxes_create", Destructive = false, OpenWorld = true)]
    public static async Task<CallToolResult?> AgentMail_Pods_Inboxes_Create(
        [Description("Pod ID that will own the inbox.")] string podId,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Optional username of the address. Randomly generated by AgentMail when omitted.")] string? username = null,
        [Description("Optional domain of the address. Must be a verified domain. Defaults to agentmail.to when omitted.")] string? domain = null,
        [Description("Optional display name, for example Display Name <username@domain.com>.")] string? displayName = null,
        [Description("Optional client-provided inbox idempotency/reference id.")] string? clientId = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
            await requestContext.WithStructuredContent(async () =>
            {
                var (typed, _, _) = await requestContext.Server.TryElicit(new AgentMailCreatePodInboxRequest
                {
                    PodId = podId,
                    Username = username,
                    Domain = domain,
                    DisplayName = displayName,
                    ClientId = clientId
                }, cancellationToken);

                AgentMailHelpers.Require(typed.PodId, nameof(podId));
                var client = serviceProvider.GetRequiredService<AgentMailClient>();
                var response = await client.PostAsync($"/v0/pods/{AgentMailHelpers.EscapePath(typed.PodId)}/inboxes", BuildCreateInboxBody(typed), cancellationToken);
                return response.StructuredOrStatus("create pod inbox");
            }));

    [Description("Delete an AgentMail pod-scoped inbox after explicit confirmation using the shared delete confirmation helper.")]
    [McpServerTool(Title = "AgentMail delete pod inbox", Name = "agentmail_pods_inboxes_delete", Destructive = true, OpenWorld = true)]
    public static async Task<CallToolResult?> AgentMail_Pods_Inboxes_Delete(
        [Description("Pod ID that owns the inbox.")] string podId,
        [Description("Inbox ID to delete from the pod.")] string inboxId,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
        {
            AgentMailHelpers.Require(podId, nameof(podId));
            AgentMailHelpers.Require(inboxId, nameof(inboxId));
            var client = serviceProvider.GetRequiredService<AgentMailClient>();
            return await requestContext.ConfirmAndDeleteAsync<ConfirmDeleteAgentMailPodInbox>(
                inboxId,
                async ct => _ = await client.DeleteAsync($"/v0/pods/{AgentMailHelpers.EscapePath(podId)}/inboxes/{AgentMailHelpers.EscapePath(inboxId)}", ct),
                $"AgentMail pod inbox '{inboxId}' deleted successfully.",
                cancellationToken);
        });

    [Description("Update AgentMail message labels. Inputs are confirmed via elicitation before the PATCH request is sent.")]
    [McpServerTool(Title = "AgentMail update message labels", Name = "agentmail_inboxes_messages_update", Destructive = false, OpenWorld = true)]
    public static async Task<CallToolResult?> AgentMail_Inboxes_Messages_Update(
        [Description("Inbox ID containing the message.")] string inboxId,
        [Description("Message ID to update.")] string messageId,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Optional labels to add, comma/semicolon/newline separated.")] string? addLabels = null,
        [Description("Optional labels to remove, comma/semicolon/newline separated.")] string? removeLabels = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
            await requestContext.WithStructuredContent(async () =>
            {
                var (typed, _, _) = await requestContext.Server.TryElicit(new AgentMailUpdateMessageRequest
                {
                    InboxId = inboxId,
                    MessageId = messageId,
                    AddLabels = addLabels,
                    RemoveLabels = removeLabels
                }, cancellationToken);

                AgentMailHelpers.Require(typed.InboxId, nameof(inboxId));
                AgentMailHelpers.Require(typed.MessageId, nameof(messageId));
                var body = AgentMailHelpers.BuildMessageLabelsBody(typed.AddLabels, typed.RemoveLabels);
                AgentMailHelpers.EnsureBody(body, "At least one label update is required: addLabels or removeLabels.");

                var client = serviceProvider.GetRequiredService<AgentMailClient>();
                var response = await client.PatchAsync($"/v0/inboxes/{AgentMailHelpers.EscapePath(typed.InboxId)}/messages/{AgentMailHelpers.EscapePath(typed.MessageId)}", body, cancellationToken);
                return response.StructuredOrStatus("update message");
            }));

    [Description("Send an AgentMail message from an inbox. Inputs are confirmed via elicitation before the POST request is sent.")]
    [McpServerTool(Title = "AgentMail send message", Name = "agentmail_inboxes_messages_send", Destructive = false, OpenWorld = true)]
    public static async Task<CallToolResult?> AgentMail_Inboxes_Messages_Send(
        [Description("Inbox ID to send from.")] string inboxId,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Optional labels, comma/semicolon/newline separated.")] string? labels = null,
        [Description("Optional reply-to address or addresses, comma/semicolon/newline separated.")] string? replyTo = null,
        [Description("Recipient address or addresses, comma/semicolon/newline separated.")] string? to = null,
        [Description("Optional CC address or addresses, comma/semicolon/newline separated.")] string? cc = null,
        [Description("Optional BCC address or addresses, comma/semicolon/newline separated.")] string? bcc = null,
        [Description("Optional message subject.")] string? subject = null,
        [Description("Optional plain text message body.")] string? text = null,
        [Description("Optional HTML message body.")] string? html = null,
        [Description("Optional JSON array of SendAttachment objects.")] string? attachmentsJson = null,
        [Description("Optional JSON object of custom headers.")] string? headersJson = null,
        CancellationToken cancellationToken = default)
        => await SendMessageLikeAsync("send message", $"/v0/inboxes/{AgentMailHelpers.EscapePath(inboxId)}/messages/send", inboxId, null, serviceProvider, requestContext, labels, replyTo, to, cc, bcc, subject, text, html, attachmentsJson, headersJson, cancellationToken);

    [Description("Reply to an AgentMail message. Inputs are confirmed via elicitation before the POST request is sent.")]
    [McpServerTool(Title = "AgentMail reply to message", Name = "agentmail_inboxes_messages_reply", Destructive = false, OpenWorld = true)]
    public static async Task<CallToolResult?> AgentMail_Inboxes_Messages_Reply(
        [Description("Inbox ID containing the message.")] string inboxId,
        [Description("Message ID to reply to.")] string messageId,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Optional labels, comma/semicolon/newline separated.")] string? labels = null,
        [Description("Optional reply-to address or addresses, comma/semicolon/newline separated.")] string? replyTo = null,
        [Description("Optional explicit recipient address or addresses, comma/semicolon/newline separated.")] string? to = null,
        [Description("Optional CC address or addresses, comma/semicolon/newline separated.")] string? cc = null,
        [Description("Optional BCC address or addresses, comma/semicolon/newline separated.")] string? bcc = null,
        [Description("Optional reply-all flag.")] bool? replyAll = null,
        [Description("Optional plain text message body.")] string? text = null,
        [Description("Optional HTML message body.")] string? html = null,
        [Description("Optional JSON array of SendAttachment objects.")] string? attachmentsJson = null,
        [Description("Optional JSON object of custom headers.")] string? headersJson = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
            await requestContext.WithStructuredContent(async () =>
            {
                var (typed, _, _) = await requestContext.Server.TryElicit(new AgentMailReplyMessageRequest
                {
                    InboxId = inboxId,
                    MessageId = messageId,
                    Labels = labels,
                    ReplyTo = replyTo,
                    To = to,
                    Cc = cc,
                    Bcc = bcc,
                    ReplyAll = replyAll,
                    Text = text,
                    Html = html,
                    AttachmentsJson = attachmentsJson,
                    HeadersJson = headersJson
                }, cancellationToken);

                AgentMailHelpers.Require(typed.InboxId, nameof(inboxId));
                AgentMailHelpers.Require(typed.MessageId, nameof(messageId));
                var body = AgentMailHelpers.BuildReplyMessageBody(typed.Labels, typed.ReplyTo, typed.To, typed.Cc, typed.Bcc, typed.ReplyAll, typed.Text, typed.Html, typed.AttachmentsJson, typed.HeadersJson);
                AgentMailHelpers.EnsureBody(body, "At least one reply field is required.");

                var client = serviceProvider.GetRequiredService<AgentMailClient>();
                var response = await client.PostAsync($"/v0/inboxes/{AgentMailHelpers.EscapePath(typed.InboxId)}/messages/{AgentMailHelpers.EscapePath(typed.MessageId!)}/reply", body, cancellationToken);
                return response.StructuredOrStatus("reply to message");
            }));

    [Description("Reply all to an AgentMail message. Inputs are confirmed via elicitation before the POST request is sent.")]
    [McpServerTool(Title = "AgentMail reply all to message", Name = "agentmail_inboxes_messages_reply_all", Destructive = false, OpenWorld = true)]
    public static async Task<CallToolResult?> AgentMail_Inboxes_Messages_ReplyAll(
        [Description("Inbox ID containing the message.")] string inboxId,
        [Description("Message ID to reply all to.")] string messageId,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Optional labels, comma/semicolon/newline separated.")] string? labels = null,
        [Description("Optional reply-to address or addresses, comma/semicolon/newline separated.")] string? replyTo = null,
        [Description("Optional plain text message body.")] string? text = null,
        [Description("Optional HTML message body.")] string? html = null,
        [Description("Optional JSON array of SendAttachment objects.")] string? attachmentsJson = null,
        [Description("Optional JSON object of custom headers.")] string? headersJson = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
            await requestContext.WithStructuredContent(async () =>
            {
                var (typed, _, _) = await requestContext.Server.TryElicit(new AgentMailReplyAllMessageRequest
                {
                    InboxId = inboxId,
                    MessageId = messageId,
                    Labels = labels,
                    ReplyTo = replyTo,
                    Text = text,
                    Html = html,
                    AttachmentsJson = attachmentsJson,
                    HeadersJson = headersJson
                }, cancellationToken);

                AgentMailHelpers.Require(typed.InboxId, nameof(inboxId));
                AgentMailHelpers.Require(typed.MessageId, nameof(messageId));
                var body = AgentMailHelpers.BuildReplyAllMessageBody(typed.Labels, typed.ReplyTo, typed.Text, typed.Html, typed.AttachmentsJson, typed.HeadersJson);
                AgentMailHelpers.EnsureBody(body, "At least one reply-all field is required.");

                var client = serviceProvider.GetRequiredService<AgentMailClient>();
                var response = await client.PostAsync($"/v0/inboxes/{AgentMailHelpers.EscapePath(typed.InboxId)}/messages/{AgentMailHelpers.EscapePath(typed.MessageId)}/reply-all", body, cancellationToken);
                return response.StructuredOrStatus("reply all to message");
            }));

    [Description("Forward an AgentMail message. Inputs are confirmed via elicitation before the POST request is sent.")]
    [McpServerTool(Title = "AgentMail forward message", Name = "agentmail_inboxes_messages_forward", Destructive = false, OpenWorld = true)]
    public static async Task<CallToolResult?> AgentMail_Inboxes_Messages_Forward(
        [Description("Inbox ID containing the message.")] string inboxId,
        [Description("Message ID to forward.")] string messageId,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Optional labels, comma/semicolon/newline separated.")] string? labels = null,
        [Description("Optional reply-to address or addresses, comma/semicolon/newline separated.")] string? replyTo = null,
        [Description("Recipient address or addresses, comma/semicolon/newline separated.")] string? to = null,
        [Description("Optional CC address or addresses, comma/semicolon/newline separated.")] string? cc = null,
        [Description("Optional BCC address or addresses, comma/semicolon/newline separated.")] string? bcc = null,
        [Description("Optional message subject.")] string? subject = null,
        [Description("Optional plain text message body.")] string? text = null,
        [Description("Optional HTML message body.")] string? html = null,
        [Description("Optional JSON array of SendAttachment objects.")] string? attachmentsJson = null,
        [Description("Optional JSON object of custom headers.")] string? headersJson = null,
        CancellationToken cancellationToken = default)
    {
        AgentMailHelpers.Require(messageId, nameof(messageId));
        return await SendMessageLikeAsync("forward message", $"/v0/inboxes/{AgentMailHelpers.EscapePath(inboxId)}/messages/{AgentMailHelpers.EscapePath(messageId)}/forward", inboxId, messageId, serviceProvider, requestContext, labels, replyTo, to, cc, bcc, subject, text, html, attachmentsJson, headersJson, cancellationToken);
    }

    [Description("Create an AgentMail draft in an inbox. Inputs are confirmed via elicitation before the POST request is sent.")]
    [McpServerTool(Title = "AgentMail create draft", Name = "agentmail_inboxes_drafts_create", Destructive = false, OpenWorld = true)]
    public static async Task<CallToolResult?> AgentMail_Inboxes_Drafts_Create(
        [Description("Inbox ID to create the draft in.")] string inboxId,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Optional labels, comma/semicolon/newline separated.")] string? labels = null,
        [Description("Optional reply-to addresses, comma/semicolon/newline separated.")] string? replyTo = null,
        [Description("Optional recipients, comma/semicolon/newline separated.")] string? to = null,
        [Description("Optional CC recipients, comma/semicolon/newline separated.")] string? cc = null,
        [Description("Optional BCC recipients, comma/semicolon/newline separated.")] string? bcc = null,
        [Description("Optional draft subject.")] string? subject = null,
        [Description("Optional plain text draft body.")] string? text = null,
        [Description("Optional HTML draft body.")] string? html = null,
        [Description("Optional message ID being replied to.")] string? inReplyTo = null,
        [Description("Optional scheduled send timestamp in ISO 8601 format.")] string? sendAt = null,
        [Description("Optional client-provided draft idempotency/reference id.")] string? clientId = null,
        CancellationToken cancellationToken = default)
        => await DraftMutationAsync("create draft", HttpMethod.Post, $"/v0/inboxes/{AgentMailHelpers.EscapePath(inboxId)}/drafts", inboxId, null, true, serviceProvider, requestContext, labels, replyTo, to, cc, bcc, subject, text, html, inReplyTo, sendAt, clientId, cancellationToken);

    [Description("Update an AgentMail draft in an inbox. Inputs are confirmed via elicitation before the PATCH request is sent.")]
    [McpServerTool(Title = "AgentMail update draft", Name = "agentmail_inboxes_drafts_update", Destructive = false, OpenWorld = true)]
    public static async Task<CallToolResult?> AgentMail_Inboxes_Drafts_Update(
        [Description("Inbox ID containing the draft.")] string inboxId,
        [Description("Draft ID to update.")] string draftId,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Optional reply-to addresses, comma/semicolon/newline separated.")] string? replyTo = null,
        [Description("Optional recipients, comma/semicolon/newline separated.")] string? to = null,
        [Description("Optional CC recipients, comma/semicolon/newline separated.")] string? cc = null,
        [Description("Optional BCC recipients, comma/semicolon/newline separated.")] string? bcc = null,
        [Description("Optional draft subject.")] string? subject = null,
        [Description("Optional plain text draft body.")] string? text = null,
        [Description("Optional HTML draft body.")] string? html = null,
        [Description("Optional scheduled send timestamp in ISO 8601 format.")] string? sendAt = null,
        CancellationToken cancellationToken = default)
        => await DraftMutationAsync("update draft", HttpMethod.Patch, $"/v0/inboxes/{AgentMailHelpers.EscapePath(inboxId)}/drafts/{AgentMailHelpers.EscapePath(draftId)}", inboxId, draftId, false, serviceProvider, requestContext, null, replyTo, to, cc, bcc, subject, text, html, null, sendAt, null, cancellationToken);

    [Description("Delete an AgentMail draft after explicit confirmation using the shared delete confirmation helper.")]
    [McpServerTool(Title = "AgentMail delete draft", Name = "agentmail_inboxes_drafts_delete", Destructive = true, OpenWorld = true)]
    public static async Task<CallToolResult?> AgentMail_Inboxes_Drafts_Delete(
        [Description("Inbox ID containing the draft.")] string inboxId,
        [Description("Draft ID to delete.")] string draftId,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
        {
            AgentMailHelpers.Require(inboxId, nameof(inboxId));
            AgentMailHelpers.Require(draftId, nameof(draftId));
            var client = serviceProvider.GetRequiredService<AgentMailClient>();
            return await requestContext.ConfirmAndDeleteAsync<ConfirmDeleteAgentMailDraft>(
                draftId,
                async ct => _ = await client.DeleteAsync($"/v0/inboxes/{AgentMailHelpers.EscapePath(inboxId)}/drafts/{AgentMailHelpers.EscapePath(draftId)}", ct),
                $"AgentMail draft '{draftId}' deleted successfully.",
                cancellationToken);
        });

    [Description("Send an AgentMail draft. Inputs are confirmed via elicitation before the POST request is sent.")]
    [McpServerTool(Title = "AgentMail send draft", Name = "agentmail_inboxes_drafts_send", Destructive = false, OpenWorld = true)]
    public static async Task<CallToolResult?> AgentMail_Inboxes_Drafts_Send(
        [Description("Inbox ID containing the draft.")] string inboxId,
        [Description("Draft ID to send.")] string draftId,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Optional labels to add before sending, comma/semicolon/newline separated.")] string? addLabels = null,
        [Description("Optional labels to remove before sending, comma/semicolon/newline separated.")] string? removeLabels = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
            await requestContext.WithStructuredContent(async () =>
            {
                var (typed, _, _) = await requestContext.Server.TryElicit(new AgentMailSendDraftRequest
                {
                    InboxId = inboxId,
                    DraftId = draftId,
                    AddLabels = addLabels,
                    RemoveLabels = removeLabels
                }, cancellationToken);

                AgentMailHelpers.Require(typed.InboxId, nameof(inboxId));
                AgentMailHelpers.Require(typed.DraftId, nameof(draftId));
                var body = AgentMailHelpers.BuildMessageLabelsBody(typed.AddLabels, typed.RemoveLabels);

                var client = serviceProvider.GetRequiredService<AgentMailClient>();
                var response = await client.PostAsync($"/v0/inboxes/{AgentMailHelpers.EscapePath(typed.InboxId)}/drafts/{AgentMailHelpers.EscapePath(typed.DraftId)}/send", body, cancellationToken);
                return response.StructuredOrStatus("send draft");
            }));

    [Description("Delete an AgentMail thread after explicit confirmation using the shared delete confirmation helper.")]
    [McpServerTool(Title = "AgentMail delete thread", Name = "agentmail_inboxes_threads_delete", Destructive = true, OpenWorld = true)]
    public static async Task<CallToolResult?> AgentMail_Inboxes_Threads_Delete(
        [Description("Inbox ID containing the thread.")] string inboxId,
        [Description("Thread ID to delete.")] string threadId,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
        {
            AgentMailHelpers.Require(inboxId, nameof(inboxId));
            AgentMailHelpers.Require(threadId, nameof(threadId));
            var client = serviceProvider.GetRequiredService<AgentMailClient>();
            return await requestContext.ConfirmAndDeleteAsync<ConfirmDeleteAgentMailThread>(
                threadId,
                async ct => _ = await client.DeleteAsync($"/v0/inboxes/{AgentMailHelpers.EscapePath(inboxId)}/threads/{AgentMailHelpers.EscapePath(threadId)}", ct),
                $"AgentMail thread '{threadId}' deleted successfully.",
                cancellationToken);
        });

    [Description("Create an AgentMail API key. Inputs are confirmed via elicitation before the POST request is sent.")]
    [McpServerTool(Title = "AgentMail create API key", Name = "agentmail_api_keys_create", Destructive = false, OpenWorld = true)]
    public static async Task<CallToolResult?> AgentMail_ApiKeys_Create(
        [Description("Name for the API key.")] string name,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
            await requestContext.WithStructuredContent(async () =>
            {
                var (typed, _, _) = await requestContext.Server.TryElicit(new AgentMailCreateApiKeyRequest
                {
                    Name = name
                }, cancellationToken);

                AgentMailHelpers.Require(typed.Name, nameof(name));
                var client = serviceProvider.GetRequiredService<AgentMailClient>();
                var response = await client.PostAsync("/v0/api-keys", new JsonObject { ["name"] = typed.Name }, cancellationToken);
                return response.StructuredOrStatus("create API key");
            }));

    [Description("Delete an AgentMail API key after explicit confirmation using the shared delete confirmation helper.")]
    [McpServerTool(Title = "AgentMail delete API key", Name = "agentmail_api_keys_delete", Destructive = true, OpenWorld = true)]
    public static async Task<CallToolResult?> AgentMail_ApiKeys_Delete(
        [Description("API key id to delete.")] string apiKey,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
        {
            AgentMailHelpers.Require(apiKey, nameof(apiKey));
            var client = serviceProvider.GetRequiredService<AgentMailClient>();
            return await requestContext.ConfirmAndDeleteAsync<ConfirmDeleteAgentMailApiKey>(
                apiKey,
                async ct => _ = await client.DeleteAsync($"/v0/api-keys/{AgentMailHelpers.EscapePath(apiKey)}", ct),
                $"AgentMail API key '{apiKey}' deleted successfully.",
                cancellationToken);
        });

    private static async Task<CallToolResult?> SendMessageLikeAsync(
        string operation,
        string path,
        string inboxId,
        string? messageId,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        string? labels,
        string? replyTo,
        string? to,
        string? cc,
        string? bcc,
        string? subject,
        string? text,
        string? html,
        string? attachmentsJson,
        string? headersJson,
        CancellationToken cancellationToken)
        => await requestContext.WithExceptionCheck(async () =>
            await requestContext.WithStructuredContent(async () =>
            {
                var (typed, _, _) = await requestContext.Server.TryElicit(new AgentMailSendMessageRequest
                {
                    InboxId = inboxId,
                    MessageId = messageId,
                    Labels = labels,
                    ReplyTo = replyTo,
                    To = to,
                    Cc = cc,
                    Bcc = bcc,
                    Subject = subject,
                    Text = text,
                    Html = html,
                    AttachmentsJson = attachmentsJson,
                    HeadersJson = headersJson
                }, cancellationToken);

                AgentMailHelpers.Require(typed.InboxId, nameof(inboxId));
                var body = AgentMailHelpers.BuildSendMessageBody(typed.Labels, typed.ReplyTo, typed.To, typed.Cc, typed.Bcc, typed.Subject, typed.Text, typed.Html, typed.AttachmentsJson, typed.HeadersJson);
                AgentMailHelpers.EnsureBody(body, $"At least one {operation} field is required.");

                var client = serviceProvider.GetRequiredService<AgentMailClient>();
                var response = await client.PostAsync(path, body, cancellationToken);
                return response.StructuredOrStatus(operation);
            }));

    private static async Task<CallToolResult?> DraftMutationAsync(
        string operation,
        HttpMethod method,
        string path,
        string inboxId,
        string? draftId,
        bool includeCreateOnlyFields,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        string? labels,
        string? replyTo,
        string? to,
        string? cc,
        string? bcc,
        string? subject,
        string? text,
        string? html,
        string? inReplyTo,
        string? sendAt,
        string? clientId,
        CancellationToken cancellationToken)
        => await requestContext.WithExceptionCheck(async () =>
            await requestContext.WithStructuredContent(async () =>
            {
                var (typed, _, _) = await requestContext.Server.TryElicit(new AgentMailDraftRequest
                {
                    InboxId = inboxId,
                    DraftId = draftId,
                    Labels = labels,
                    ReplyTo = replyTo,
                    To = to,
                    Cc = cc,
                    Bcc = bcc,
                    Subject = subject,
                    Text = text,
                    Html = html,
                    InReplyTo = inReplyTo,
                    SendAt = sendAt,
                    ClientId = clientId
                }, cancellationToken);

                AgentMailHelpers.Require(typed.InboxId, nameof(inboxId));
                if (!string.IsNullOrWhiteSpace(draftId)) AgentMailHelpers.Require(typed.DraftId, nameof(draftId));
                var body = AgentMailHelpers.BuildDraftBody(typed.Labels, typed.ReplyTo, typed.To, typed.Cc, typed.Bcc, typed.Subject, typed.Text, typed.Html, typed.InReplyTo, typed.SendAt, typed.ClientId, includeCreateOnlyFields);
                AgentMailHelpers.EnsureBody(body, $"At least one {operation} field is required.");

                var client = serviceProvider.GetRequiredService<AgentMailClient>();
                var response = method == HttpMethod.Post
                    ? await client.PostAsync(path, body, cancellationToken)
                    : await client.PatchAsync(path, body, cancellationToken);
                return response.StructuredOrStatus(operation);
            }));

    private static JsonObject BuildCreateInboxBody(IAgentMailCreateInboxInput input)
    {
        var body = new JsonObject();
        if (!string.IsNullOrWhiteSpace(input.Username)) body["username"] = input.Username.Trim();
        if (!string.IsNullOrWhiteSpace(input.Domain)) body["domain"] = input.Domain.Trim();
        if (!string.IsNullOrWhiteSpace(input.DisplayName)) body["display_name"] = input.DisplayName.Trim();
        if (!string.IsNullOrWhiteSpace(input.ClientId)) body["client_id"] = input.ClientId.Trim();
        return body;
    }
}

internal interface IAgentMailCreateInboxInput
{
    string? Username { get; }
    string? Domain { get; }
    string? DisplayName { get; }
    string? ClientId { get; }
}

[Description("Please confirm the AgentMail create inbox request.")]
internal class AgentMailCreateInboxRequest : IAgentMailCreateInboxInput
{
    [JsonPropertyName("username")]
    [Description("Optional username of the address.")]
    public string? Username { get; set; }

    [JsonPropertyName("domain")]
    [Description("Optional verified domain of the address.")]
    public string? Domain { get; set; }

    [JsonPropertyName("display_name")]
    [Description("Optional display name.")]
    public string? DisplayName { get; set; }

    [JsonPropertyName("client_id")]
    [Description("Optional client-provided reference id.")]
    public string? ClientId { get; set; }
}

[Description("Please confirm the AgentMail create pod inbox request.")]
internal sealed class AgentMailCreatePodInboxRequest : AgentMailCreateInboxRequest
{
    [JsonPropertyName("pod_id")]
    [Required]
    [Description("Pod ID that will own the inbox.")]
    public string PodId { get; set; } = string.Empty;
}

[Description("Please confirm the AgentMail update inbox request.")]
internal sealed class AgentMailUpdateInboxRequest
{
    [JsonPropertyName("inbox_id")]
    [Required]
    public string InboxId { get; set; } = string.Empty;

    [JsonPropertyName("display_name")]
    [Required]
    public string DisplayName { get; set; } = string.Empty;
}

[Description("Please confirm the AgentMail update message request.")]
internal sealed class AgentMailUpdateMessageRequest
{
    [JsonPropertyName("inbox_id")]
    [Required]
    public string InboxId { get; set; } = string.Empty;

    [JsonPropertyName("message_id")]
    [Required]
    public string MessageId { get; set; } = string.Empty;

    [JsonPropertyName("add_labels")]
    public string? AddLabels { get; set; }

    [JsonPropertyName("remove_labels")]
    public string? RemoveLabels { get; set; }
}

[Description("Please confirm the AgentMail send/forward message request.")]
internal class AgentMailSendMessageRequest
{
    [JsonPropertyName("inbox_id")]
    [Required]
    public string InboxId { get; set; } = string.Empty;

    [JsonPropertyName("message_id")]
    public string? MessageId { get; set; }

    [JsonPropertyName("labels")]
    public string? Labels { get; set; }

    [JsonPropertyName("reply_to")]
    public string? ReplyTo { get; set; }

    [JsonPropertyName("to")]
    public string? To { get; set; }

    [JsonPropertyName("cc")]
    public string? Cc { get; set; }

    [JsonPropertyName("bcc")]
    public string? Bcc { get; set; }

    [JsonPropertyName("subject")]
    public string? Subject { get; set; }

    [JsonPropertyName("text")]
    public string? Text { get; set; }

    [JsonPropertyName("html")]
    public string? Html { get; set; }

    [JsonPropertyName("attachments_json")]
    public string? AttachmentsJson { get; set; }

    [JsonPropertyName("headers_json")]
    public string? HeadersJson { get; set; }
}

[Description("Please confirm the AgentMail reply message request.")]
internal sealed class AgentMailReplyMessageRequest : AgentMailSendMessageRequest
{
    [JsonPropertyName("reply_all")]
    public bool? ReplyAll { get; set; }
}

[Description("Please confirm the AgentMail reply-all message request.")]
internal sealed class AgentMailReplyAllMessageRequest
{
    [JsonPropertyName("inbox_id")]
    [Required]
    public string InboxId { get; set; } = string.Empty;

    [JsonPropertyName("message_id")]
    [Required]
    public string MessageId { get; set; } = string.Empty;

    [JsonPropertyName("labels")]
    public string? Labels { get; set; }

    [JsonPropertyName("reply_to")]
    public string? ReplyTo { get; set; }

    [JsonPropertyName("text")]
    public string? Text { get; set; }

    [JsonPropertyName("html")]
    public string? Html { get; set; }

    [JsonPropertyName("attachments_json")]
    public string? AttachmentsJson { get; set; }

    [JsonPropertyName("headers_json")]
    public string? HeadersJson { get; set; }
}

[Description("Please confirm the AgentMail draft mutation request.")]
internal sealed class AgentMailDraftRequest
{
    [JsonPropertyName("inbox_id")]
    [Required]
    public string InboxId { get; set; } = string.Empty;

    [JsonPropertyName("draft_id")]
    public string? DraftId { get; set; }

    [JsonPropertyName("labels")]
    public string? Labels { get; set; }

    [JsonPropertyName("reply_to")]
    public string? ReplyTo { get; set; }

    [JsonPropertyName("to")]
    public string? To { get; set; }

    [JsonPropertyName("cc")]
    public string? Cc { get; set; }

    [JsonPropertyName("bcc")]
    public string? Bcc { get; set; }

    [JsonPropertyName("subject")]
    public string? Subject { get; set; }

    [JsonPropertyName("text")]
    public string? Text { get; set; }

    [JsonPropertyName("html")]
    public string? Html { get; set; }

    [JsonPropertyName("in_reply_to")]
    public string? InReplyTo { get; set; }

    [JsonPropertyName("send_at")]
    public string? SendAt { get; set; }

    [JsonPropertyName("client_id")]
    public string? ClientId { get; set; }
}

[Description("Please confirm the AgentMail send draft request.")]
internal sealed class AgentMailSendDraftRequest
{
    [JsonPropertyName("inbox_id")]
    [Required]
    public string InboxId { get; set; } = string.Empty;

    [JsonPropertyName("draft_id")]
    [Required]
    public string DraftId { get; set; } = string.Empty;

    [JsonPropertyName("add_labels")]
    public string? AddLabels { get; set; }

    [JsonPropertyName("remove_labels")]
    public string? RemoveLabels { get; set; }
}

[Description("Please confirm the AgentMail create API key request.")]
internal sealed class AgentMailCreateApiKeyRequest
{
    [JsonPropertyName("name")]
    [Required]
    public string Name { get; set; } = string.Empty;
}
