using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using MCPhappey.Common.Extensions;
using MCPhappey.Core.Extensions;
using Microsoft.Extensions.DependencyInjection;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;

namespace MCPhappey.Tools.RegoloAI.Images;

public static class RegoloAIImages
{

    [Description("Generate image(s) with Regolo AI. Supports prompt text and optional prompt file URL (SharePoint/OneDrive/public). Uploads result image(s) and returns resource link block(s).")]
    [McpServerTool(Title = "Generate image with Regolo AI", Name = "regoloai_images_create", Destructive = false)]
    public static async Task<CallToolResult?> RegoloAI_Images_Create(
        [Description("Prompt for image generation. If promptFileUrl is supplied, file contents are appended.")] string prompt,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Model identifier, for example: Qwen-Image")] string model = "Qwen-Image",
        [Description("Number of images to generate (keep small for faster response).")]
        [Range(1, 10)] int n = 1,
        [Description("Image size. Supported: 256x256, 512x512, 1024x1024.")] string size = "1024x1024",
        [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
        {
            var allowedSizes = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                "256x256",
                "512x512",
                "1024x1024"
            };

            if (!allowedSizes.Contains(size))
                throw new Exception("Invalid size. Supported values: 256x256, 512x512, 1024x1024.");

            var finalPrompt = prompt?.Trim() ?? string.Empty;
           
            if (string.IsNullOrWhiteSpace(finalPrompt))
                throw new Exception("Prompt is required. Provide prompt text and/or a promptFileUrl with readable text.");

            var regolo = serviceProvider.GetRequiredService<RegoloAIClient>();
            var response = await regolo.PostJsonAsync("v1/images/generations", new
            {
                prompt = finalPrompt,
                n,
                model,
                size
            }, cancellationToken);

            var data = response?["data"]?.AsArray() ?? throw new Exception("No image data returned from Regolo AI.");
            if (data.Count == 0)
                throw new Exception("No image data returned from Regolo AI.");

            var safeBaseName = filename?.ToOutputFileName() ?? requestContext.ToOutputFileName();
            var uploadedLinks = new List<ResourceLinkBlock>();

            for (var i = 0; i < data.Count; i++)
            {
                var b64 = data[i]?["b64_json"]?.GetValue<string>();
                if (string.IsNullOrWhiteSpace(b64))
                    continue;

                var bytes = Convert.FromBase64String(b64);
                var uploaded = await requestContext.Server.Upload(
                    serviceProvider,
                    $"{safeBaseName}-{i + 1}.png",
                    BinaryData.FromBytes(bytes),
                    cancellationToken);

                if (uploaded != null)
                    uploadedLinks.Add(uploaded);
            }

            if (uploadedLinks.Count == 0)
                throw new Exception("Image generation succeeded but upload failed.");

            return uploadedLinks.ToResourceLinkCallToolResponse();
        });
}

