using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using MCPhappey.Common.Extensions;
using MCPhappey.Core.Extensions;
using MCPhappey.Core.Services;
using Microsoft.Extensions.DependencyInjection;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;

namespace MCPhappey.Tools.Nebius;

public static class NebiusImages
{
    [Description("Generate image(s) with Nebius, upload outputs to SharePoint/OneDrive, and return only resource link blocks.")]
    [McpServerTool(Title = "Generate images with Nebius", Name = "nebius_images_generate", Destructive = false, OpenWorld = true)]
    public static async Task<CallToolResult?> Nebius_Images_Generate(
        [Description("Prompt text describing the image to generate.")] string prompt,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Model ID to use.")] string model = "black-forest-labs/flux-schnell",
        [Description("Image width in pixels (64-2048).")][Range(64, 2048)] int width = 512,
        [Description("Image height in pixels (64-2048).")][Range(64, 2048)] int height = 512,
        [Description("Number of inference steps (1-80).")][Range(1, 80)] int? numInferenceSteps = null,
        [Description("Random seed (-1 for random).")][Range(-1, int.MaxValue)] int seed = -1,
        [Description("Guidance scale (0-100).")][Range(0, 100)] double? guidanceScale = null,
        [Description("Negative prompt for undesired content.")] string? negativePrompt = null,
        [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
    {
        var (typed, notAccepted, _) = await requestContext.Server.TryElicit(
            new NebiusImageGenerateRequest
            {
                Prompt = prompt,
                Model = model,
                Width = width,
                Height = height,
                NumInferenceSteps = numInferenceSteps,
                Seed = seed,
                GuidanceScale = guidanceScale,
                NegativePrompt = negativePrompt,
                Filename = filename
            },
            cancellationToken);

        if (string.IsNullOrWhiteSpace(typed.Prompt))
            throw new ValidationException("prompt is required.");

        if (string.IsNullOrWhiteSpace(typed.Model))
            throw new ValidationException("model is required.");

        var client = serviceProvider.GetRequiredService<NebiusClient>();
        var body = new
        {
            model = typed.Model,
            prompt = typed.Prompt,
            width = typed.Width,
            height = typed.Height,
            num_inference_steps = typed.NumInferenceSteps,
            seed = typed.Seed,
            guidance_scale = typed.GuidanceScale,
            negative_prompt = typed.NegativePrompt,
            response_format = "url"
        };

        JsonNode? response = await client.PostAsync("v1/images/generations", body, null, cancellationToken);
        var data = response?["data"]?.AsArray() ?? throw new Exception("No image data returned from Nebius.");
        if (data.Count == 0)
            throw new Exception("No image data returned from Nebius.");

        var downloadService = serviceProvider.GetRequiredService<DownloadService>();
        var links = new List<ResourceLinkBlock>();
        var baseName = typed.Filename?.ToOutputFileName() ?? requestContext.ToOutputFileName();

        var i = 0;
        foreach (var item in data)
        {
            i++;
            var url = item?["url"]?.GetValue<string>();
            if (string.IsNullOrWhiteSpace(url))
                continue;

            var files = await downloadService.DownloadContentAsync(serviceProvider, requestContext.Server, url, cancellationToken);
            var file = files.FirstOrDefault();
            if (file == null)
                continue;

            var ext = GetImageExtension(file.Filename, file.MimeType);
            var uploaded = await requestContext.Server.Upload(
                serviceProvider,
                $"{baseName}-{i}{ext}",
                BinaryData.FromBytes(file.Contents.ToArray()),
                cancellationToken);

            if (uploaded != null)
                links.Add(uploaded);
        }

        if (links.Count == 0)
            throw new Exception("Image generation succeeded but no outputs could be uploaded.");

        return links.ToResourceLinkCallToolResponse();
    });

    private static string GetImageExtension(string? filename, string? mimeType)
    {
        var ext = Path.GetExtension(filename ?? string.Empty);
        if (!string.IsNullOrWhiteSpace(ext))
            return ext;

        return mimeType?.ToLowerInvariant() switch
        {
            "image/jpeg" => ".jpg",
            "image/webp" => ".webp",
            "image/gif" => ".gif",
            "image/bmp" => ".bmp",
            _ => ".png"
        };
    }
}

[Description("Please confirm the Nebius image generation request.")]
public class NebiusImageGenerateRequest
{
    [JsonPropertyName("model")]
    [Required]
    [Description("Model ID to use.")]
    public string Model { get; set; } = "black-forest-labs/flux-schnell";

    [JsonPropertyName("prompt")]
    [Required]
    [Description("Text description of the image to generate.")]
    public string Prompt { get; set; } = default!;

    [JsonPropertyName("width")]
    [Description("Image width in pixels.")]
    public int Width { get; set; } = 512;

    [JsonPropertyName("height")]
    [Description("Image height in pixels.")]
    public int Height { get; set; } = 512;

    [JsonPropertyName("num_inference_steps")]
    [Description("Number of inference steps.")]
    public int? NumInferenceSteps { get; set; }

    [JsonPropertyName("seed")]
    [Description("Random seed for generation (-1 for random).")]
    public int Seed { get; set; } = -1;

    [JsonPropertyName("guidance_scale")]
    [Description("Guidance scale for prompt adherence.")]
    public double? GuidanceScale { get; set; }

    [JsonPropertyName("negative_prompt")]
    [Description("Negative prompt for undesired content.")]
    public string? NegativePrompt { get; set; }

    [JsonPropertyName("filename")]
    [Description("Output filename without extension.")]
    public string? Filename { get; set; }
}
