using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using MCPhappey.Core.Extensions;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;
using MCPhappey.Tools.Runway.Video;
using MCPhappey.Tools.AIML.Video;

namespace MCPhappey.Tools.AI;

public static class MovieMakerPlugin
{
    [Description("Generate a short AI video using MiniMax Hailuo-02. Optionally specify first and last frame images to guide the animation.")]
    [McpServerTool(
        Title = "Generate video with AI/ML MiniMax Hailuo-02",
        Name = "moviemaker_minimax_hailuo02_generate",
        Destructive = false)]
    public static async Task<CallToolResult?> MovieMaker_MiniMaxHailuo02Generate(
        [Description("Prompt describing the video content (scene, subject, or action)."), MaxLength(2000)] string prompt,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Optional image URL or SharePoint/OneDrive link for the first frame.")] string firstFrameImage,
        [Description("Optional image URL or SharePoint/OneDrive link for the last frame.")] string lastImageUrl,
        [Description("Video duration in seconds (6–10).")] MiniMaxDuration duration = MiniMaxDuration.Seconds6,
        [Description("Video resolution. Default: 768P.")] MiniMaxResolution resolution = MiniMaxResolution.P768,
        [Description("Automatically optimize prompt for better quality (default: true).")] bool promptOptimizer = true,
        [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
        [Description("If true, the tool waits until the generation is completed before returning. Default: false.")] bool waitUntilCompleted = false,
        CancellationToken cancellationToken = default) =>
        await requestContext.WithExceptionCheck(async () =>
        await AIMLVideo.AIMLVideo_MiniMaxHailuo02Generate(prompt, serviceProvider, requestContext, firstFrameImage, lastImageUrl,
            duration, resolution, promptOptimizer, filename, waitUntilCompleted, cancellationToken));

    // ---------- IMAGE → VIDEO ----------
    [Description("Start an image-to-video task on Runway. Returns the task id.")]
    [McpServerTool(Title = "Generate video with Runway", Name = "moviemaker_image_to_video_create",
        OpenWorld = true,
        ReadOnly = false,
        Destructive = false)]
    public static async Task<CallToolResult?> MovieMaker_ImageToVideoCreate(
        IEnumerable<string> promptImages,
        string? promptText,
        RunwayImageToVideoModel? model,
        [Description("Ratio.")] RunwayImageToVideoRatio? ratio,
        int? duration,
        int? seed,
        IServiceProvider sp,
        RequestContext<CallToolRequestParams> rc,
        [Description("Wait until the fully completed and upload outputs.")]
        bool? waitUntilCompleted,
        CancellationToken ct = default)
        => await rc.WithExceptionCheck(async () =>
    {
        if (promptImages == null || !promptImages.Any() || promptImages.Count() != 2)
            throw new ValidationException("Two images are required. These images will be used as the first and the last frame of the video.");

        return await RunwayVideo.Runway_ImageToVideoCreate(promptImages, promptText, model, ratio, duration, seed,
            sp, rc, waitUntilCompleted, ct);
    });

 /*   [Description("Generate a smooth AI video transition between two images using Google Veo 3.1 Fast.")]
    [McpServerTool(
      Title = "Generate video with AI/ML Google Veo 3.1 Fast",
      Name = "moviemaker_video_google_veo31fast",
      Destructive = false)]
    public static async Task<CallToolResult?> MovieMaker_GoogleVeo31Fast(
      [Description("Prompt describing the visual story or transition between the first and last image."), MaxLength(4000)] string prompt,
      [Description("URL of the first input image (at least 720p).")] string imageUrl,
      [Description("URL or Base64 string of the final image to morph into.")] string lastImageUrl,
      IServiceProvider serviceProvider,
      RequestContext<CallToolRequestParams> requestContext,
      [Description("Aspect ratio of the generated video. Default: 16:9")] VeoAspectRatio aspectRatio = VeoAspectRatio.Ratio_16x9,
      [Description("Duration of the video in seconds. Only 8 supported.")] int duration = 8,
      [Description("Video resolution (720p or 1080p). Default: 1080p")] VeoResolution resolution = VeoResolution.p1080,
      [Description("Generate audio for the video. Default: true")] bool generateAudio = true,
      [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
      [Description("If true, the tool waits until the generation is completed before returning.")] bool waitUntilCompleted = false,
      CancellationToken cancellationToken = default)
      => await AIMLVideo.AIMLVideo_GoogleVeo31FastFirstLastGenerate(prompt, imageUrl, lastImageUrl, serviceProvider, requestContext,
            aspectRatio, duration, resolution, generateAudio, filename, waitUntilCompleted, cancellationToken);*/
}