using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using MCPhappey.Core.Extensions;
using Microsoft.Extensions.DependencyInjection;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;
using MCPhappey.Common.Extensions;

namespace MCPhappey.Tools.Runware.Audio;

public static class RunwareAudio
{
    [Description("Create audio using Runware models.")]
    [McpServerTool(
           Title = "Create Runware audio",
           Name = "runware_audio_create",
           OpenWorld = true,
           ReadOnly = false,
           Destructive = false)]
    public static async Task<CallToolResult?> RunwareAudio_Create(
           [Description("Prompt describing the audio to generate (music, sound, or speech).")] string prompt,
           [Description("Runware model identifier, e.g. elevenlabs:1@1.")] string model,
           IServiceProvider serviceProvider,
           RequestContext<CallToolRequestParams> requestContext,
           [Description("Audio duration in seconds (10–300).")] float duration = 30,
           [Description("Number of audio results to generate.")] int numberResults = 1,
           [Description("Output format (MP3).")] string outputFormat = "MP3",
           [Description("Output type (URL, dataURI, base64Data).")] string outputType = "URL",
           [Description("Audio sample rate in Hz (8000–48000).")] int sampleRate = 44100,
           [Description("Audio bitrate in kbps (32–320).")] int bitrate = 128,
           [Description("Optional negative prompt to exclude elements.")] string? negativePrompt = null,
           [Description("Optional seed for reproducibility.")] int? seed = null,
           [Description("Filename (without extension). Defaults to autogenerated name.")] string? filename = null,
           CancellationToken cancellationToken = default)
           => await requestContext.WithExceptionCheck(async () =>
               await requestContext.WithStructuredContent(async () =>
               {
                   // 🧠 1. Elicit structured inputs when missing
                   var (typed, notAccepted, result) = await requestContext.Server.TryElicit(
                       new RunwareNewAudio
                       {
                           PositivePrompt = prompt,
                           NegativePrompt = negativePrompt,
                           Model = model,
                           Duration = duration,
                           NumberResults = numberResults,
                           OutputFormat = outputFormat,
                           OutputType = outputType,
                           SampleRate = sampleRate,
                           Bitrate = bitrate,
                           Seed = seed,
                           Filename = filename
                       },
                       cancellationToken);

                   var client = serviceProvider.GetRequiredService<RunwareClient>();
                   typed.Filename ??= requestContext.ToOutputFileName("mp3");

                   // 🧱 2. Build task payload
                   var task = new
                   {
                       taskUUID = Guid.NewGuid().ToString(),
                       taskType = "audioInference",
                       model = typed.Model,
                       positivePrompt = typed.PositivePrompt,
                       negativePrompt = typed.NegativePrompt,
                       duration = typed.Duration,
                       numberResults = typed.NumberResults,
                       outputType = typed.OutputType,
                       outputFormat = typed.OutputFormat,
                       audioSettings = new
                       {
                           sampleRate = typed.SampleRate,
                           bitrate = typed.Bitrate
                       },
                       seed = typed.Seed
                   };

                   var payload = new[] { task };

                   // 🚀 3. Submit to Runware
                   var resultNode = await client.PostAsync(payload, cancellationToken)
                       ?? throw new Exception("Runware returned no response.");

                   // 🎧 4. Return raw JSON for UI or toolchain processing
                   return resultNode.ToCallToolResponse();
               }));


    [Description("Please fill in the Runware audio generation request details.")]
    public class RunwareNewAudio
    {
        [JsonPropertyName("positivePrompt")]
        [Required]
        [Description("Prompt describing the audio to generate (music, sound, or speech).")]
        public string PositivePrompt { get; set; } = default!;

        [JsonPropertyName("negativePrompt")]
        [Description("Prompt describing what to avoid in the generated audio.")]
        public string? NegativePrompt { get; set; }

        [JsonPropertyName("model")]
        [Required]
        [Description("Runware model identifier, e.g. elevenlabs:1@1.")]
        public string Model { get; set; } = default!;

        [JsonPropertyName("duration")]
        [Range(10, 300)]
        [Description("Audio duration in seconds.")]
        public float Duration { get; set; } = 30;

        [JsonPropertyName("numberResults")]
        [Range(1, 3)]
        [Description("Number of audio results to generate.")]
        public int NumberResults { get; set; } = 1;

        [JsonPropertyName("outputType")]
        [Description("Output type (URL, dataURI, base64Data). Defaults to URL.")]
        public string OutputType { get; set; } = "URL";

        [JsonPropertyName("outputFormat")]
        [Description("Output format (MP3). Defaults to MP3.")]
        public string OutputFormat { get; set; } = "MP3";

        [JsonPropertyName("sampleRate")]
        [Range(8000, 48000)]
        [Description("Audio sample rate in Hz (default 44100).")]
        public int SampleRate { get; set; } = 44100;

        [JsonPropertyName("bitrate")]
        [Range(32, 320)]
        [Description("Audio bitrate in kbps (default 128).")]
        public int Bitrate { get; set; } = 128;

        [JsonPropertyName("seed")]
        [Description("Optional seed for deterministic generation.")]
        public int? Seed { get; set; }

        [JsonPropertyName("filename")]
        [Description("Filename (without extension). Defaults to autogenerated name.")]
        public string? Filename { get; set; }
    }
}