using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Net.Http.Headers;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using MCPhappey.Common.Extensions;
using MCPhappey.Core.Extensions;
using Microsoft.Extensions.DependencyInjection;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;

namespace MCPhappey.Tools.CaseDev;

public static class CaseDevSuperDoc
{
    [Description("Convert documents between formats with Case.dev SuperDoc. POST parameters are always confirmed via elicitation, fileUrl inputs support SharePoint and OneDrive, and output files are uploaded before returning a resource link.")]
    [McpServerTool(Title = "Case.dev SuperDoc convert", Name = "casedev_superdoc_convert", Destructive = false, OpenWorld = true)]
    public static async Task<CallToolResult?> CaseDev_SuperDoc_Convert(
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Optional SharePoint, OneDrive, or public HTTP fileUrl for the source document.")] string? fileUrl = null,
        [Description("Optional base64 source document when fileUrl is not used.")] string? fileBase64 = null,
        [Description("Source format: docx, md, or html.")] string from = "docx",
        [Description("Target format: pdf or docx.")] string to = "pdf",
        [Description("Optional output filename without extension. Defaults to autogenerated name.")] string? filename = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
        {
            var (typed, notAccepted, _) = await requestContext.Server.TryElicit(new CaseDevSuperDocConvertRequest
            {
                FileUrl = fileUrl,
                FileBase64 = fileBase64,
                From = from,
                To = to,
                Filename = filename
            }, cancellationToken);

            if (notAccepted != null) return notAccepted;
            if (typed == null) return "No input data provided".ToErrorCallToolResponse();

            var normalizedFrom = NormalizeConvertFrom(typed.From);
            var normalizedTo = NormalizeConvertTo(typed.To);
            ValidateSingleDocumentSource(typed.FileUrl, typed.FileBase64, allowDocumentUrl: false, typed.DocumentUrl);

            byte[] bytes;
            string sourceFilename;
            string sourceMimeType;

            if (!string.IsNullOrWhiteSpace(typed.FileUrl))
            {
                var file = await CaseDevHelpers.DownloadSingleFileAsync(serviceProvider, requestContext, typed.FileUrl!, cancellationToken);
                bytes = file.Contents.ToArray();
                sourceFilename = string.IsNullOrWhiteSpace(file.Filename) ? $"superdoc-source.{normalizedFrom}" : file.Filename;
                sourceMimeType = string.IsNullOrWhiteSpace(file.MimeType) ? sourceFilename.ResolveMimeFromExtension() : file.MimeType;
            }
            else
            {
                bytes = Convert.FromBase64String(typed.FileBase64!);
                sourceFilename = $"superdoc-source.{normalizedFrom}";
                sourceMimeType = sourceFilename.ResolveMimeFromExtension();
            }

            using var form = new MultipartFormDataContent();
            var fileContent = new ByteArrayContent(bytes);
            fileContent.Headers.ContentType = MediaTypeHeaderValue.Parse(sourceMimeType);
            form.Add(fileContent, "file", sourceFilename);
            form.Add(new StringContent(normalizedFrom), "from");
            form.Add(new StringContent(normalizedTo), "to");

            var client = serviceProvider.GetRequiredService<CaseDevClient>();
            var response = await client.SendMultipartAsync("/superdoc/v1/convert", form, cancellationToken);

            var baseFilename = CaseDevHelpers.BuildBaseFilename(requestContext, typed.Filename);
            return await response.ToUploadOrStructuredResultAsync(requestContext, serviceProvider, baseFilename, normalizedTo, cancellationToken);
        });

    [Description("Populate DOCX template fields with Case.dev SuperDoc annotations. POST parameters are always confirmed via elicitation, fileUrl inputs support SharePoint and OneDrive, and output files are uploaded before returning a resource link.")]
    [McpServerTool(Title = "Case.dev SuperDoc annotate", Name = "casedev_superdoc_annotate", Destructive = false, OpenWorld = true)]
    public static async Task<CallToolResult?> CaseDev_SuperDoc_Annotate(
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Fields JSON array string for SuperDoc annotate.")] string fieldsJson,
        [Description("Optional SharePoint, OneDrive, or public HTTP fileUrl for the DOCX template.")] string? fileUrl = null,
        [Description("Optional public URL for the DOCX template when fileUrl is not used.")] string? documentUrl = null,
        [Description("Optional base64 DOCX template when no URL is used.")] string? documentBase64 = null,
        [Description("Output format: docx or pdf.")] string outputFormat = "docx",
        [Description("Optional output filename without extension. Defaults to autogenerated name.")] string? filename = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
        {
            var (typed, notAccepted, _) = await requestContext.Server.TryElicit(new CaseDevSuperDocAnnotateRequest
            {
                FieldsJson = fieldsJson,
                FileUrl = fileUrl,
                DocumentUrl = documentUrl,
                DocumentBase64 = documentBase64,
                OutputFormat = outputFormat,
                Filename = filename
            }, cancellationToken);

            if (notAccepted != null) return notAccepted;
            if (typed == null) return "No input data provided".ToErrorCallToolResponse();

            ValidateSingleDocumentSource(typed.FileUrl, typed.DocumentBase64, allowDocumentUrl: true, typed.DocumentUrl);
            var fields = CaseDevHelpers.ParseArray(typed.FieldsJson, nameof(fieldsJson));
            var normalizedOutput = NormalizeAnnotateOutput(typed.OutputFormat);

            var document = new JsonObject();
            if (!string.IsNullOrWhiteSpace(typed.FileUrl))
            {
                var file = await CaseDevHelpers.DownloadSingleFileAsync(serviceProvider, requestContext, typed.FileUrl!, cancellationToken);
                document["base64"] = Convert.ToBase64String(file.Contents.ToArray());
            }
            else if (!string.IsNullOrWhiteSpace(typed.DocumentBase64))
            {
                document["base64"] = typed.DocumentBase64;
            }
            else
            {
                document["url"] = typed.DocumentUrl;
            }

            var body = new JsonObject
            {
                ["document"] = document,
                ["fields"] = fields,
                ["output_format"] = normalizedOutput
            };

            var client = serviceProvider.GetRequiredService<CaseDevClient>();
            var response = await client.SendJsonAsync(HttpMethod.Post, "/superdoc/v1/annotate", body, cancellationToken);
            var baseFilename = CaseDevHelpers.BuildBaseFilename(requestContext, typed.Filename);
            return await response.ToUploadOrStructuredResultAsync(requestContext, serviceProvider, baseFilename, normalizedOutput, cancellationToken);
        });

    private static string NormalizeConvertFrom(string? from)
        => from?.Trim().ToLowerInvariant() switch
        {
            "docx" => "docx",
            "md" => "md",
            "html" => "html",
            _ => throw new ValidationException("from must be one of: docx, md, html.")
        };

    private static string NormalizeConvertTo(string? to)
        => to?.Trim().ToLowerInvariant() switch
        {
            "pdf" => "pdf",
            "docx" => "docx",
            _ => throw new ValidationException("to must be one of: pdf, docx.")
        };

    private static string NormalizeAnnotateOutput(string? outputFormat)
        => outputFormat?.Trim().ToLowerInvariant() switch
        {
            "docx" => "docx",
            "pdf" => "pdf",
            _ => throw new ValidationException("outputFormat must be one of: docx, pdf.")
        };

    private static void ValidateSingleDocumentSource(string? fileUrl, string? documentBase64, bool allowDocumentUrl, string? documentUrl)
    {
        var count = 0;
        if (!string.IsNullOrWhiteSpace(fileUrl)) count++;
        if (!string.IsNullOrWhiteSpace(documentBase64)) count++;
        if (allowDocumentUrl && !string.IsNullOrWhiteSpace(documentUrl)) count++;

        if (count == 0)
            throw new ValidationException(allowDocumentUrl
                ? "Provide exactly one of fileUrl, documentUrl, or documentBase64."
                : "Provide exactly one of fileUrl or fileBase64.");

        if (count > 1)
            throw new ValidationException(allowDocumentUrl
                ? "fileUrl, documentUrl, and documentBase64 are mutually exclusive."
                : "fileUrl and fileBase64 are mutually exclusive.");
    }
}

[Description("Please confirm the Case.dev SuperDoc convert request.")]
public sealed class CaseDevSuperDocConvertRequest
{
    [JsonPropertyName("fileUrl")]
    [Description("Optional SharePoint, OneDrive, or public HTTP fileUrl for the source document.")]
    public string? FileUrl { get; set; }

    [JsonPropertyName("fileBase64")]
    [Description("Optional base64 source document when fileUrl is not used.")]
    public string? FileBase64 { get; set; }

    [JsonPropertyName("documentUrl")]
    [Description("Reserved internal field.")]
    public string? DocumentUrl { get; set; }

    [JsonPropertyName("from")]
    [Required]
    [Description("Source format: docx, md, or html.")]
    public string From { get; set; } = "docx";

    [JsonPropertyName("to")]
    [Required]
    [Description("Target format: pdf or docx.")]
    public string To { get; set; } = "pdf";

    [JsonPropertyName("filename")]
    [Description("Optional output filename without extension.")]
    public string? Filename { get; set; }
}

[Description("Please confirm the Case.dev SuperDoc annotate request.")]
public sealed class CaseDevSuperDocAnnotateRequest
{
    [JsonPropertyName("fieldsJson")]
    [Required]
    [Description("Fields JSON array string for SuperDoc annotate.")]
    public string FieldsJson { get; set; } = "[]";

    [JsonPropertyName("fileUrl")]
    [Description("Optional SharePoint, OneDrive, or public HTTP fileUrl for the DOCX template.")]
    public string? FileUrl { get; set; }

    [JsonPropertyName("documentUrl")]
    [Description("Optional public URL for the DOCX template when fileUrl is not used.")]
    public string? DocumentUrl { get; set; }

    [JsonPropertyName("documentBase64")]
    [Description("Optional base64 DOCX template when no URL is used.")]
    public string? DocumentBase64 { get; set; }

    [JsonPropertyName("outputFormat")]
    [Required]
    [Description("Output format: docx or pdf.")]
    public string OutputFormat { get; set; } = "docx";

    [JsonPropertyName("filename")]
    [Description("Optional output filename without extension.")]
    public string? Filename { get; set; }
}
