using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using MCPhappey.Common.Extensions;
using MCPhappey.Core.Extensions;
using Microsoft.Extensions.DependencyInjection;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;

namespace MCPhappey.Tools.CaseDev;

public static class CaseDevFormat
{
    [Description("Format Markdown, JSON, or text into a PDF, DOCX, or HTML preview with Case.dev. POST parameters are always confirmed via elicitation. When the response is a file or HTML, it is uploaded and returned as a resource link.")]
    [McpServerTool(Title = "Case.dev format document", Name = "casedev_format_document", Destructive = false, OpenWorld = true)]
    public static async Task<CallToolResult?> CaseDev_Format_Document(
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Optional inline source content. Provide this or fileUrl.")] string? content = null,
        [Description("Optional SharePoint, OneDrive, or public HTTP fileUrl to scrape as source content. Provide this or content.")] string? fileUrl = null,
        [Description("Desired output format: pdf, docx, or html_preview.")] string outputFormat = "pdf",
        [Description("Input format: md, json, or text.")] string inputFormat = "md",
        [Description("Optional JSON object string for Case.dev formatting options.")] string? optionsJson = null,
        [Description("Optional output filename without extension. Defaults to autogenerated name.")] string? filename = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
        {
            var (typed, notAccepted, _) = await requestContext.Server.TryElicit(new CaseDevFormatDocumentRequest
            {
                Content = content,
                FileUrl = fileUrl,
                OutputFormat = outputFormat,
                InputFormat = inputFormat,
                OptionsJson = optionsJson,
                Filename = filename
            }, cancellationToken);

            if (notAccepted != null) return notAccepted;
            if (typed == null) return "No input data provided".ToErrorCallToolResponse();

            var normalizedOutput = NormalizeOutputFormat(typed.OutputFormat);
            var normalizedInput = NormalizeInputFormat(typed.InputFormat);

            string finalContent;
            if (!string.IsNullOrWhiteSpace(typed.Content))
            {
                finalContent = typed.Content;
            }
            else if (!string.IsNullOrWhiteSpace(typed.FileUrl))
            {
                finalContent = await CaseDevHelpers.ScrapeTextFromFileUrlAsync(serviceProvider, requestContext, typed.FileUrl, cancellationToken);
            }
            else
            {
                throw new ValidationException("Either content or fileUrl is required.");
            }

            var body = new JsonObject
            {
                ["content"] = finalContent,
                ["output_format"] = normalizedOutput,
                ["input_format"] = normalizedInput
            };

            if (CaseDevHelpers.ParseObject(typed.OptionsJson, nameof(optionsJson)) is { } options)
                body["options"] = options;

            var client = serviceProvider.GetRequiredService<CaseDevClient>();
            var response = await client.SendJsonAsync(HttpMethod.Post, "/format/v1/document", body, cancellationToken);

            var baseFilename = CaseDevHelpers.BuildBaseFilename(requestContext, typed.Filename);
            var preferredExtension = normalizedOutput switch
            {
                "docx" => ".docx",
                "html_preview" => ".html",
                _ => ".pdf"
            };

            return await response.ToUploadOrStructuredResultAsync(requestContext, serviceProvider, baseFilename, preferredExtension, cancellationToken);
        });

    [Description("Create a reusable Case.dev format template. POST parameters are always confirmed via elicitation and JSON responses are returned as structured content.")]
    [McpServerTool(Title = "Case.dev create format template", Name = "casedev_format_templates_create", Destructive = false, OpenWorld = true)]
    public static async Task<CallToolResult?> CaseDev_Format_CreateTemplate(
        [Description("Template name.")] string name,
        [Description("Template type: caption, signature, letterhead, certificate, footer, or custom.")] string type,
        [Description("Template content with {{variable}} placeholders.")] string content,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Optional template description.")] string? description = null,
        [Description("Optional JSON object string for template styles.")] string? stylesJson = null,
        [Description("Optional variables as comma, semicolon, or newline separated values.")] string? variables = null,
        [Description("Optional tags as comma, semicolon, or newline separated values.")] string? tags = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
            await requestContext.WithStructuredContent(async () =>
            {
                var (typed, notAccepted, _) = await requestContext.Server.TryElicit(new CaseDevFormatTemplateCreateRequest
                {
                    Name = name,
                    Type = type,
                    Content = content,
                    Description = description,
                    StylesJson = stylesJson,
                    Variables = variables,
                    Tags = tags
                }, cancellationToken);

                if (string.IsNullOrWhiteSpace(typed.Name))
                    throw new ValidationException("name is required.");
                if (string.IsNullOrWhiteSpace(typed.Type))
                    throw new ValidationException("type is required.");
                if (string.IsNullOrWhiteSpace(typed.Content))
                    throw new ValidationException("content is required.");

                var body = new JsonObject
                {
                    ["name"] = typed.Name,
                    ["type"] = NormalizeTemplateType(typed.Type),
                    ["content"] = typed.Content
                };

                if (!string.IsNullOrWhiteSpace(typed.Description)) body["description"] = typed.Description;
                if (CaseDevHelpers.ParseObject(typed.StylesJson, nameof(stylesJson)) is { } styles) body["styles"] = styles;
                if (CaseDevHelpers.ToJsonArray(CaseDevHelpers.ParseDelimited(typed.Variables)) is { } variableArray) body["variables"] = variableArray;
                if (CaseDevHelpers.ToJsonArray(CaseDevHelpers.ParseDelimited(typed.Tags)) is { } tagArray) body["tags"] = tagArray;

                var client = serviceProvider.GetRequiredService<CaseDevClient>();
                var response = await client.SendJsonAsync(HttpMethod.Post, "/format/v1/templates", body, cancellationToken);
                return response.Json ?? new JsonObject();
            }));

    private static string NormalizeOutputFormat(string? outputFormat)
        => outputFormat?.Trim().ToLowerInvariant() switch
        {
            "pdf" => "pdf",
            "docx" => "docx",
            "html_preview" => "html_preview",
            _ => throw new ValidationException("outputFormat must be one of: pdf, docx, html_preview.")
        };

    private static string NormalizeInputFormat(string? inputFormat)
        => inputFormat?.Trim().ToLowerInvariant() switch
        {
            "md" => "md",
            "json" => "json",
            "text" => "text",
            _ => throw new ValidationException("inputFormat must be one of: md, json, text.")
        };

    private static string NormalizeTemplateType(string? type)
        => type?.Trim().ToLowerInvariant() switch
        {
            "caption" => "caption",
            "signature" => "signature",
            "letterhead" => "letterhead",
            "certificate" => "certificate",
            "footer" => "footer",
            "custom" => "custom",
            _ => throw new ValidationException("type must be one of: caption, signature, letterhead, certificate, footer, custom.")
        };
}

[Description("Please confirm the Case.dev document formatting request.")]
public sealed class CaseDevFormatDocumentRequest
{
    [JsonPropertyName("content")]
    [Description("Optional inline source content.")]
    public string? Content { get; set; }

    [JsonPropertyName("fileUrl")]
    [Description("Optional SharePoint, OneDrive, or public HTTP fileUrl to scrape as source content.")]
    public string? FileUrl { get; set; }

    [JsonPropertyName("outputFormat")]
    [Required]
    [Description("Desired output format: pdf, docx, or html_preview.")]
    public string OutputFormat { get; set; } = "pdf";

    [JsonPropertyName("inputFormat")]
    [Required]
    [Description("Input format: md, json, or text.")]
    public string InputFormat { get; set; } = "md";

    [JsonPropertyName("optionsJson")]
    [Description("Optional JSON object string for Case.dev formatting options.")]
    public string? OptionsJson { get; set; }

    [JsonPropertyName("filename")]
    [Description("Optional output filename without extension.")]
    public string? Filename { get; set; }
}

[Description("Please confirm the Case.dev format template creation request.")]
public sealed class CaseDevFormatTemplateCreateRequest
{
    [JsonPropertyName("name")]
    [Required]
    [Description("Template name.")]
    public string Name { get; set; } = string.Empty;

    [JsonPropertyName("type")]
    [Required]
    [Description("Template type.")]
    public string Type { get; set; } = string.Empty;

    [JsonPropertyName("content")]
    [Required]
    [Description("Template content with {{variable}} placeholders.")]
    public string Content { get; set; } = string.Empty;

    [JsonPropertyName("description")]
    [Description("Optional template description.")]
    public string? Description { get; set; }

    [JsonPropertyName("stylesJson")]
    [Description("Optional JSON object string for template styles.")]
    public string? StylesJson { get; set; }

    [JsonPropertyName("variables")]
    [Description("Optional variables as comma, semicolon, or newline separated values.")]
    public string? Variables { get; set; }

    [JsonPropertyName("tags")]
    [Description("Optional tags as comma, semicolon, or newline separated values.")]
    public string? Tags { get; set; }
}
