using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Net.Http.Headers;
using System.Text.Json.Serialization;
using MCPhappey.Common.Extensions;
using MCPhappey.Core.Extensions;
using MCPhappey.Core.Services;
using Microsoft.Extensions.DependencyInjection;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;

namespace MCPhappey.Tools.Decart.Images;

public static class DecartImages
{
    private const string BaseUrl = "https://api.decart.ai";
    private const string T2IPath = "/v1/generate/lucy-pro-t2i";
    private const string I2IPath = "/v1/generate/lucy-pro-i2i";

    [Description("Generate an image from text using Decart Lucy Pro (T2I).")]
    [McpServerTool(Title = "Generate image with Decart", Name = "decart_images_generate", Destructive = false)]
    public static async Task<CallToolResult?> Decart_Images_Generate(
        [Description("Prompt describing the image to generate.")] string prompt,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Output resolution: 480p or 720p.")] string resolution = "720p",
        [Description("Random seed (0 to 4294967295).")][Range(0, 4294967295)] long? seed = null,
        [Description("Whether Decart should enhance the prompt.")] bool enhancePrompt = true,
        [Description("Image orientation. Example: landscape.")] string orientation = "landscape",
        [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
    {
        var (typed, notAccepted, _) = await requestContext.Server.TryElicit(
            new DecartGenerateImageRequest
            {
                Prompt = prompt,
                Resolution = resolution,
                Seed = seed,
                EnhancePrompt = enhancePrompt,
                Orientation = orientation,
                Filename = filename
            },
            cancellationToken);

        if (notAccepted != null) return notAccepted;
        if (typed == null) return "No input data provided".ToErrorCallToolResponse();

        ValidateResolution(typed.Resolution);
        ValidateSeed(typed.Seed);

        var settings = serviceProvider.GetService<DecartSettings>()
            ?? throw new InvalidOperationException("No DecartSettings found in service provider");

        using var client = new HttpClient { BaseAddress = new Uri(BaseUrl) };
        client.DefaultRequestHeaders.Add("X-API-KEY", settings.ApiKey);

        var body = new List<KeyValuePair<string, string>>
        {
            new("prompt", typed.Prompt),
            new("resolution", typed.Resolution),
            new("enhance_prompt", typed.EnhancePrompt.ToString().ToLowerInvariant()),
            new("orientation", typed.Orientation)
        };

        if (typed.Seed.HasValue)
            body.Add(new KeyValuePair<string, string>("seed", typed.Seed.Value.ToString()));

        using var request = new HttpRequestMessage(HttpMethod.Post, T2IPath)
        {
            Content = new FormUrlEncodedContent(body)
        };

        using var response = await client.SendAsync(request, cancellationToken);
        var bytes = await response.Content.ReadAsByteArrayAsync(cancellationToken);

        if (!response.IsSuccessStatusCode)
            throw new Exception($"{response.StatusCode}: {System.Text.Encoding.UTF8.GetString(bytes)}");

        var finalName = (typed.Filename?.ToOutputFileName() ?? requestContext.ToOutputFileName("png")) + ".png";

        var uploaded = await requestContext.Server.Upload(
            serviceProvider,
            finalName,
            BinaryData.FromBytes(bytes),
            cancellationToken);

        var links = new List<ResourceLinkBlock>();
        if (uploaded != null) links.Add(uploaded);
        return links.ToResourceLinkCallToolResponse();
    });

    [Description("Edit an image with Decart Lucy Pro (I2I) using fileUrl input.")]
    [McpServerTool(Title = "Edit image with Decart", Name = "decart_images_edit", Destructive = false)]
    public static async Task<CallToolResult?> Decart_Images_Edit(
        [Description("Prompt describing the edit to apply.")] string prompt,
        [Description("Input image URL. SharePoint and OneDrive secure links are supported.")] string fileUrl,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Output resolution: 480p or 720p.")] string resolution = "720p",
        [Description("Random seed (0 to 4294967295).")][Range(0, 4294967295)] long? seed = null,
        [Description("Whether Decart should enhance the prompt.")] bool enhancePrompt = true,
        [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
    {
        var (typed, notAccepted, _) = await requestContext.Server.TryElicit(
            new DecartEditImageRequest
            {
                Prompt = prompt,
                FileUrl = fileUrl,
                Resolution = resolution,
                Seed = seed,
                EnhancePrompt = enhancePrompt,
                Filename = filename
            },
            cancellationToken);

        if (notAccepted != null) return notAccepted;
        if (typed == null) return "No input data provided".ToErrorCallToolResponse();

        if (string.IsNullOrWhiteSpace(typed.FileUrl))
            throw new ValidationException("fileUrl is required.");

        ValidateResolution(typed.Resolution);
        ValidateSeed(typed.Seed);

        var downloadService = serviceProvider.GetRequiredService<DownloadService>();
        var files = await downloadService.DownloadContentAsync(serviceProvider, requestContext.Server, typed.FileUrl, cancellationToken);
        var sourceImage = files.FirstOrDefault() ?? throw new InvalidOperationException("No file content could be downloaded from fileUrl.");

        var settings = serviceProvider.GetService<DecartSettings>()
            ?? throw new InvalidOperationException("No DecartSettings found in service provider");

        using var client = new HttpClient { BaseAddress = new Uri(BaseUrl) };
        client.DefaultRequestHeaders.Add("X-API-KEY", settings.ApiKey);

        using var form = new MultipartFormDataContent();
        form.Add(new StringContent(typed.Prompt), "prompt");
        form.Add(new StringContent(typed.Resolution), "resolution");
        form.Add(new StringContent(typed.EnhancePrompt.ToString().ToLowerInvariant()), "enhance_prompt");

        if (typed.Seed.HasValue)
            form.Add(new StringContent(typed.Seed.Value.ToString()), "seed");

        var imageContent = new ByteArrayContent(sourceImage.Contents.ToArray());
        if (!string.IsNullOrWhiteSpace(sourceImage.MimeType))
            imageContent.Headers.ContentType = new MediaTypeHeaderValue(sourceImage.MimeType);

        form.Add(imageContent, "data", sourceImage.Filename ?? "input.png");

        using var request = new HttpRequestMessage(HttpMethod.Post, I2IPath)
        {
            Content = form
        };

        using var response = await client.SendAsync(request, cancellationToken);
        var bytes = await response.Content.ReadAsByteArrayAsync(cancellationToken);

        if (!response.IsSuccessStatusCode)
            throw new Exception($"{response.StatusCode}: {System.Text.Encoding.UTF8.GetString(bytes)}");

        var finalName = (typed.Filename?.ToOutputFileName() ?? requestContext.ToOutputFileName("png")) + ".png";

        var uploaded = await requestContext.Server.Upload(
            serviceProvider,
            finalName,
            BinaryData.FromBytes(bytes),
            cancellationToken);

        var links = new List<ResourceLinkBlock>();
        if (uploaded != null) links.Add(uploaded);
        return links.ToResourceLinkCallToolResponse();
    });

    private static void ValidateResolution(string resolution)
    {
        if (string.IsNullOrWhiteSpace(resolution))
            throw new ValidationException("resolution is required.");

        if (!string.Equals(resolution, "480p", StringComparison.OrdinalIgnoreCase)
            && !string.Equals(resolution, "720p", StringComparison.OrdinalIgnoreCase))
            throw new ValidationException("resolution must be 480p or 720p.");
    }

    private static void ValidateSeed(long? seed)
    {
        if (!seed.HasValue) return;
        if (seed < 0 || seed > 4294967295)
            throw new ValidationException("seed must be between 0 and 4294967295.");
    }
}

[Description("Please confirm the Decart text-to-image request.")]
public sealed class DecartGenerateImageRequest
{
    [JsonPropertyName("prompt")]
    [Required]
    [Description("Text description of the image to generate.")]
    public string Prompt { get; set; } = default!;

    [JsonPropertyName("resolution")]
    [Required]
    [Description("Output size. Allowed values: 480p or 720p.")]
    public string Resolution { get; set; } = "720p";

    [JsonPropertyName("seed")]
    [Description("Random seed for reproducible results (0 to 4294967295).")]
    public long? Seed { get; set; }

    [JsonPropertyName("enhancePrompt")]
    [Description("Whether to let Decart enhance the prompt.")]
    public bool EnhancePrompt { get; set; } = true;

    [JsonPropertyName("orientation")]
    [Required]
    [Description("Orientation of the generated image. Example: landscape.")]
    public string Orientation { get; set; } = "landscape";

    [JsonPropertyName("filename")]
    [Description("Output filename without extension.")]
    public string? Filename { get; set; }
}

[Description("Please confirm the Decart image-to-image request.")]
public sealed class DecartEditImageRequest
{
    [JsonPropertyName("prompt")]
    [Required]
    [Description("Text description of the image edits to apply.")]
    public string Prompt { get; set; } = default!;

    [JsonPropertyName("fileUrl")]
    [Required]
    [Description("Input image URL. SharePoint and OneDrive secure links are supported.")]
    public string FileUrl { get; set; } = default!;

    [JsonPropertyName("resolution")]
    [Required]
    [Description("Output size. Allowed values: 480p or 720p.")]
    public string Resolution { get; set; } = "720p";

    [JsonPropertyName("seed")]
    [Description("Random seed for reproducible results (0 to 4294967295).")]
    public long? Seed { get; set; }

    [JsonPropertyName("enhancePrompt")]
    [Description("Whether to let Decart enhance the prompt.")]
    public bool EnhancePrompt { get; set; } = true;

    [JsonPropertyName("filename")]
    [Description("Output filename without extension.")]
    public string? Filename { get; set; }
}

