using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using MCPhappey.Core.Extensions;
using Microsoft.Extensions.DependencyInjection;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;
using MCPhappey.Common.Extensions;

namespace MCPhappey.Tools.Runware.Video;

public static class RunwareVideo
{
    [Description("Create a new video using Runware models.")]
    [McpServerTool(
       Title = "Create Runware Video",
       Name = "runware_video_create",
       OpenWorld = true,
       ReadOnly = false,
       Destructive = false)]
    public static async Task<CallToolResult?> RunwareVideo_Create(
       [Description("Prompt describing the video to generate.")]
        string prompt,
       [Description("Runware model identifier, e.g. runware/flux1s-video.")]
        string model,
       IServiceProvider serviceProvider,
       RequestContext<CallToolRequestParams> requestContext,
       [Description("Video duration in seconds.")] int? seconds = null,
       [Description("Frames per second.")] int? fps = null,
       [Description("Video width in pixels.")] int? width = null,
       [Description("Video height in pixels.")] int? height = null,
       [Description("Optional negative prompt.")] string? negativePrompt = null,
       [Description("Optional random seed for deterministic results.")] int? seed = null,
       [Description("Filename (without extension). Defaults to autogenerated name.")] string? filename = null,
       CancellationToken cancellationToken = default)
       => await requestContext.WithExceptionCheck(async () =>
           await requestContext.WithStructuredContent(async () =>
           {
               // 🧠 1. Elicit structured defaults if not all provided
               var (typed, notAccepted, result) = await requestContext.Server.TryElicit(
                   new RunwareNewVideo
                   {
                       Prompt = prompt,
                       Model = model,
                       Seconds = seconds ?? 10,
                       Fps = fps ?? 24,
                       Width = width ?? 1024,
                       Height = height ?? 576,
                       NegativePrompt = negativePrompt,
                       Seed = seed,
                       Filename = filename
                   },
                   cancellationToken);


               var client = serviceProvider.GetRequiredService<RunwareClient>();
               typed.Filename ??= requestContext.ToOutputFileName("mp4");

               // 🧱 2. Build the Runware task
               var task = new
               {
                   taskUUID = Guid.NewGuid().ToString(),
                   taskType = "videoInference",
                   model = typed.Model,
                   prompt = typed.Prompt,
                   negativePrompt = typed.NegativePrompt,
                   seed = typed.Seed,
                   seconds = typed.Seconds,
                   width = typed.Width,
                   height = typed.Height,
                   fps = typed.Fps
               };

               var payload = new[] { task };

               // 🚀 3. Submit the job
               var resultNode = await client.PostAsync(payload, cancellationToken)
                   ?? throw new Exception("Runware returned no response.");

               return resultNode.ToCallToolResponse();
           }));

    [Description("Please fill in the Runware video generation request details.")]
    public class RunwareNewVideo
    {
        [JsonPropertyName("prompt")]
        [Required]
        [Description("Prompt describing the video to generate.")]
        public string Prompt { get; set; } = default!;

        [JsonPropertyName("model")]
        [Required]
        [Description("Runware model identifier, e.g. runware/flux1s-video.")]
        public string Model { get; set; } = default!;

        [JsonPropertyName("seconds")]
        [Description("Video duration in seconds. Defaults to 10.")]
        public int? Seconds { get; set; } = 10;

        [JsonPropertyName("fps")]
        [Description("Frames per second. Defaults to 24.")]
        public int? Fps { get; set; } = 24;

        [JsonPropertyName("width")]
        [Description("Video width in pixels. Defaults to 1024.")]
        public int? Width { get; set; } = 1024;

        [JsonPropertyName("height")]
        [Description("Video height in pixels. Defaults to 576.")]
        public int? Height { get; set; } = 576;

        [JsonPropertyName("negativePrompt")]
        [Description("Optional negative prompt to exclude elements.")]
        public string? NegativePrompt { get; set; }

        [JsonPropertyName("seed")]
        [Description("Optional random seed for deterministic generation.")]
        public int? Seed { get; set; }

        [JsonPropertyName("waitUntilCompleted")]
        [Description("Wait until generation completes (default: true).")]
        public bool WaitUntilCompleted { get; set; } = true;

        [JsonPropertyName("filename")]
        [Description("Filename (without extension). Defaults to autogenerated name.")]
        public string? Filename { get; set; }
    }
}