using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;
using MCPhappey.Common.Extensions;
using MCPhappey.Core.Extensions;
using Microsoft.Extensions.DependencyInjection;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;

namespace MCPhappey.Tools.AIML.Video;

public static partial class AIMLVideo
{
    private static readonly string PIXVERSE_BASE_URL = "https://api.aimlapi.com/v2/generate/video/pixverse/generation";

    [Description("Generate a short AI video using PixVerse v5. Provide a prompt describing the scene, subject, or action. Returns a generation ID for asynchronous processing.")]
    [McpServerTool(
        Title = "Generate video with PixVerse v5",
        Name = "aiml_video_pixverse_generate",
        Destructive = false)]
    public static async Task<CallToolResult?> AIMLVideo_PixVerseGenerate(
        [Description("Prompt describing the video content (scene, subject, action, atmosphere, etc.)."), MaxLength(4000)] string prompt,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Aspect ratio of the generated video. Default: 16:9")] AspectRatio aspectRatio = AspectRatio.Ratio_16x9,
        [Description("Video resolution. Default: 720p")] Resolution resolution = Resolution.p720,
        [Description("Duration of the output video in seconds (5 or 8).")] Duration duration = Duration.Seconds5,
        [Description("Optional description of what to avoid in the video.")] string? negativePrompt = null,
        [Description("Visual style of the generated video.")] VideoStyle style = VideoStyle.Anime,
        [Description("Optional seed for deterministic results.")] int? seed = null,
        [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
    {
        var settings = serviceProvider.GetRequiredService<AIMLSettings>();

        var aiml = serviceProvider.GetRequiredService<AIMLClient>();
        // Step 1: Ask user for missing input
        var (typed, notAccepted, _) = await requestContext.Server.TryElicit(
            new AIMLPixVerseVideoRequest
            {
                Prompt = prompt,
                AspectRatio = aspectRatio,
                Resolution = resolution,
                Duration = duration,
                NegativePrompt = negativePrompt,
                Style = style,
                Seed = seed,
                Filename = filename?.ToOutputFileName() ?? requestContext.ToOutputFileName("mp4")
            },
            cancellationToken);

        // Step 2: Build JSON payload
        var body = new
        {
            model = "pixverse/v5/text-to-video",
            prompt = typed.Prompt,
            aspect_ratio = typed.AspectRatio.GetEnumMemberValue(),
            resolution = typed.Resolution.GetEnumMemberValue(),
            duration = (int)typed.Duration,
            negative_prompt = typed.NegativePrompt,
            style = typed.Style.GetEnumMemberValue(),
            seed = typed.Seed
        };

        var doc = await aiml.PostAsync(MINIMAX_VIDEO_URL, body, cancellationToken);
        var id = doc.RootElement.TryGetProperty("id", out var idProp)
             ? idProp.GetString()
             : null;

        if (string.IsNullOrWhiteSpace(id))
            throw new Exception("No generation ID returned from PixVerse API.");

        // Step 5: Return JSON + info text
        return doc.ToJsonContent(PIXVERSE_BASE_URL).ToCallToolResult();
    });

    // --- DTOs & Enums ---

    [Description("Please fill in the PixVerse video generation request.")]
    public class AIMLPixVerseVideoRequest
    {
        [JsonPropertyName("prompt")]
        [Required]
        [Description("Text description of the video scene or action.")]
        public string Prompt { get; set; } = default!;

        [JsonPropertyName("aspect_ratio")]
        [Required]
        [Description("Aspect ratio of the video.")]
        public AspectRatio AspectRatio { get; set; } = AspectRatio.Ratio_16x9;

        [JsonPropertyName("resolution")]
        [Required]
        [Description("Video resolution (360p–1080p).")]
        public Resolution Resolution { get; set; } = Resolution.p720;

        [JsonPropertyName("duration")]
        [Required]
        [Description("Length of video in seconds (5 or 8).")]
        public Duration Duration { get; set; } = Duration.Seconds5;

        [JsonPropertyName("negative_prompt")]
        [Description("Elements to exclude from the generated video.")]
        public string? NegativePrompt { get; set; }

        [JsonPropertyName("style")]
        [Description("Visual style of the generated video.")]
        public VideoStyle Style { get; set; } = VideoStyle.Anime;

        [JsonPropertyName("seed")]
        [Description("Seed for deterministic generation (optional).")]
        public int? Seed { get; set; }

        [JsonPropertyName("filename")]
        [Required]
        [Description("Output filename without extension.")]
        public string Filename { get; set; } = default!;
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum AspectRatio
    {
        [EnumMember(Value = "16:9")]
        Ratio_16x9,
        [EnumMember(Value = "4:3")]
        Ratio_4x3,
        [EnumMember(Value = "1:1")]
        Ratio_1x1,
        [EnumMember(Value = "3:4")]
        Ratio_3x4,
        [EnumMember(Value = "9:16")]
        Ratio_9x16,
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum Resolution
    {
        [EnumMember(Value = "360p")]
        p360,
        [EnumMember(Value = "540p")]
        p540,
        [EnumMember(Value = "720p")]
        p720,
        [EnumMember(Value = "1080p")]
        p1080
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum Duration
    {
        [EnumMember(Value = "5")]
        Seconds5 = 5,
        [EnumMember(Value = "8")]
        Seconds8 = 8
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum VideoStyle
    {
        [EnumMember(Value = "anime")]
        Anime,
        [EnumMember(Value = "3d_animation")]
        Animation3D,
        [EnumMember(Value = "clay")]
        Clay,
        [EnumMember(Value = "comic")]
        Comic,
        [EnumMember(Value = "cyberpunk")]
        Cyberpunk
    }
}