using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;
using MCPhappey.Common.Extensions;
using MCPhappey.Core.Extensions;
using MCPhappey.Core.Services;
using Microsoft.Extensions.DependencyInjection;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;

namespace MCPhappey.Tools.AIML.Video;

public static partial class AIMLVideo
{
    private static readonly string BASE_URL = "https://api.aimlapi.com/v2/video/generations";

   

    [Description("Generate a short AI video using SberAI Kandinsky 5 (text-to-video). Provide a prompt describing the scene or action. Returns a generation ID for asynchronous processing.")]
    [McpServerTool(
        Title = "Generate video with SberAI Kandinsky 5",
        Name = "aiml_video_sberai_kandinsky5_generate",
        Destructive = false)]
    public static async Task<CallToolResult?> AIMLVideo_SberAIKandinsky5Generate(
        [Description("Prompt describing the video content (scene, subject, or action)."), MaxLength(4000)] string prompt,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Aspect ratio of the generated video. Default: 16:9")] SberAspectRatio aspectRatio = SberAspectRatio.Ratio_16x9,
        [Description("Length of the generated video in seconds (5 or 10).")] SberDuration duration = SberDuration.Seconds5,
        [Description("Number of inference steps. Higher values improve quality but take longer. Default: 30"), Range(1, 1000)] int numInferenceSteps = 30,
        [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
    {
        var settings = serviceProvider.GetRequiredService<AIMLSettings>();
        var clientFactory = serviceProvider.GetRequiredService<IHttpClientFactory>();

        // Step 1: Ask user for any missing input
        var (typed, notAccepted, _) = await requestContext.Server.TryElicit(
            new AIMLSberVideoRequest
            {
                Prompt = prompt,
                AspectRatio = aspectRatio,
                Duration = duration,
                NumInferenceSteps = numInferenceSteps,
                Filename = filename?.ToOutputFileName()
                    ?? requestContext.ToOutputFileName("mp4")
            },
            cancellationToken);

        // Step 2: Build JSON payload
        var body = new
        {
            model = "sber-ai/kandinsky5-t2v",
            prompt = typed.Prompt,
            aspect_ratio = typed.AspectRatio.GetEnumMemberValue(),
            duration = (int)typed.Duration,
            num_inference_steps = typed.NumInferenceSteps
        };

        var aiml = serviceProvider.GetRequiredService<AIMLClient>();
        var doc = await aiml.PostAsync(BASE_URL, body, cancellationToken);

        var id = doc.RootElement.TryGetProperty("id", out var idProp)
            ? idProp.GetString()
            : null;

        if (string.IsNullOrWhiteSpace(id))
            throw new Exception("No generation ID returned from SberAI API.");

        // Step 5: Return result
        return doc.ToJsonContent(BASE_URL).ToCallToolResult();
    });

    // --- DTOs & Enums ---

    [Description("Please fill in the SberAI Kandinsky 5 video generation request.")]
    public class AIMLSberVideoRequest
    {
        [JsonPropertyName("prompt")]
        [Required]
        [Description("Text description of the scene or action to generate.")]
        public string Prompt { get; set; } = default!;

        [JsonPropertyName("aspect_ratio")]
        [Required]
        [Description("Aspect ratio of the video.")]
        public SberAspectRatio AspectRatio { get; set; } = SberAspectRatio.Ratio_16x9;

        [JsonPropertyName("duration")]
        [Required]
        [Description("Video duration in seconds.")]
        public SberDuration Duration { get; set; } = SberDuration.Seconds5;

        [JsonPropertyName("num_inference_steps")]
        [Range(1, 1000)]
        [Description("Number of inference steps for sampling. Higher = better quality, slower generation.")]
        public int NumInferenceSteps { get; set; } = 30;

        [JsonPropertyName("filename")]
        [Required]
        [Description("Output filename without extension.")]
        public string Filename { get; set; } = default!;
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum SberAspectRatio
    {
        [EnumMember(Value = "16:9")]
        Ratio_16x9,
        [EnumMember(Value = "9:16")]
        Ratio_9x16,
        [EnumMember(Value = "1:1")]
        Ratio_1x1
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum SberDuration
    {
        [EnumMember(Value = "5")]
        Seconds5 = 5,
        [EnumMember(Value = "10")]
        Seconds10 = 10
    }

    [Description("Generate a short AI video using SberAI Kandinsky 5 Distill (text-to-video). Provide a prompt describing the scene or action. Returns a generation ID for asynchronous processing.")]
    [McpServerTool(
     Title = "Generate video with SberAI Kandinsky 5 Distill",
     Name = "aiml_video_sberai_kandinsky5_distill_generate",
     Destructive = false)]
    public static async Task<CallToolResult?> AIMLVideo_SberAIDistillGenerate(
     [Description("Prompt describing the video content (scene, subject, or action)."), MaxLength(4000)] string prompt,
     IServiceProvider serviceProvider,
     RequestContext<CallToolRequestParams> requestContext,
     [Description("Aspect ratio of the generated video. Default: 16:9")] DistillAspectRatio aspectRatio = DistillAspectRatio.Ratio_16x9,
     [Description("Length of the generated video in seconds (5 or 10).")] DistillDuration duration = DistillDuration.Seconds5,
     [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
     CancellationToken cancellationToken = default)
     => await requestContext.WithExceptionCheck(async () =>
 {
     var settings = serviceProvider.GetRequiredService<AIMLSettings>();
     var clientFactory = serviceProvider.GetRequiredService<IHttpClientFactory>();
     var aiml = serviceProvider.GetRequiredService<AIMLClient>();
     // Step 1: Ask user for missing inputs
     var (typed, notAccepted, _) = await requestContext.Server.TryElicit(
         new AIMLDistillVideoRequest
         {
             Prompt = prompt,
             AspectRatio = aspectRatio,
             Duration = duration,
             Filename = filename?.ToOutputFileName() ?? requestContext.ToOutputFileName("mp4")
         },
         cancellationToken);

     // Step 2: Build JSON payload
     var body = new
     {
         model = "sber-ai/kandinsky5-distill-t2v",
         prompt = typed.Prompt,
         aspect_ratio = typed.AspectRatio.GetEnumMemberValue(),
         duration = (int)typed.Duration
     };

     var doc = await aiml.PostAsync(BASE_URL, body, cancellationToken);
     var id = doc.RootElement.TryGetProperty("id", out var idProp)
         ? idProp.GetString()
         : null;

     if (string.IsNullOrWhiteSpace(id))
         throw new Exception("No generation ID returned from Distill API.");

     // Step 5: Return response + message
     return doc.ToJsonContent(BASE_URL).ToCallToolResult();
 });

    [Description("Please fill in the SberAI Kandinsky 5 Distill video generation request.")]
    public class AIMLDistillVideoRequest
    {
        [JsonPropertyName("prompt")]
        [Required]
        [Description("Text description of the video scene or action.")]
        public string Prompt { get; set; } = default!;

        [JsonPropertyName("aspect_ratio")]
        [Required]
        [Description("Aspect ratio of the video (16:9, 9:16, or 1:1).")]
        public DistillAspectRatio AspectRatio { get; set; } = DistillAspectRatio.Ratio_16x9;

        [JsonPropertyName("duration")]
        [Required]
        [Description("Length of the video in seconds (5 or 10).")]
        public DistillDuration Duration { get; set; } = DistillDuration.Seconds5;

        [JsonPropertyName("filename")]
        [Required]
        [Description("Output filename without extension.")]
        public string Filename { get; set; } = default!;
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum DistillAspectRatio
    {
        [EnumMember(Value = "16:9")]
        Ratio_16x9,
        [EnumMember(Value = "9:16")]
        Ratio_9x16,
        [EnumMember(Value = "1:1")]
        Ratio_1x1
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum DistillDuration
    {
        [EnumMember(Value = "5")]
        Seconds5 = 5,
        [EnumMember(Value = "10")]
        Seconds10 = 10
    }

    [Description("Generate a short AI video using Krea WAN-14B (text-to-video). Duration is defined by frame count (16 fps). Returns a generation ID for asynchronous processing.")]
    [McpServerTool(
      Title = "Generate video with Krea WAN-14B",
      Name = "aiml_video_krea_wan14b_generate",
      Destructive = false)]
    public static async Task<CallToolResult?> AIMLVideo_KreaWAN14BGenerate(
      [Description("Prompt describing the video content (scene, subject, or action)."), MaxLength(4000)] string prompt,
      IServiceProvider serviceProvider,
      RequestContext<CallToolRequestParams> requestContext,
      [Description("Number of frames to generate (18–162, must be 12n+6). Default: 78"), Range(18, 162)] int numFrames = 78,
      [Description("Enable or disable prompt expansion (default: true).")] bool enablePromptExpansion = true,
      [Description("Optional seed for deterministic generation.")] int? seed = null,
      [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
      CancellationToken cancellationToken = default)
      => await requestContext.WithExceptionCheck(async () =>
  {
      ArgumentNullException.ThrowIfNullOrWhiteSpace(prompt);

      var settings = serviceProvider.GetRequiredService<AIMLSettings>();
      var clientFactory = serviceProvider.GetRequiredService<IHttpClientFactory>();

      // Step 1: Ask user for missing inputs
      var (typed, notAccepted, _) = await requestContext.Server.TryElicit(
          new AIMLKreaWAN14BVideoRequest
          {
              Prompt = prompt,
              NumFrames = numFrames,
              EnablePromptExpansion = enablePromptExpansion,
              Seed = seed,
              Filename = filename?.ToOutputFileName() ?? requestContext.ToOutputFileName("mp4")
          },
          cancellationToken);

      if (notAccepted != null) return notAccepted;
      if (typed == null) return "User input missing.".ToErrorCallToolResponse();

      // Step 2: Build JSON payload
      var body = new
      {
          model = "krea/krea-wan-14b/text-to-video",
          prompt = typed.Prompt,
          num_frames = typed.NumFrames,
          enable_prompt_expansion = typed.EnablePromptExpansion,
          seed = typed.Seed
      };

      var aiml = serviceProvider.GetRequiredService<AIMLClient>();
      var doc = await aiml.PostAsync(BASE_URL, body, cancellationToken);
      var id = doc.RootElement.TryGetProperty("id", out var idProp)
          ? idProp.GetString()
          : null;

      if (string.IsNullOrWhiteSpace(id))
          throw new Exception("No generation ID returned from Krea API.");

      // Step 5: Return JSON + info text
      return doc.ToJsonContent(BASE_URL).ToCallToolResult();
  });

    // --- DTOs & Schema ---

    [Description("Please fill in the Krea WAN-14B video generation request.")]
    public class AIMLKreaWAN14BVideoRequest
    {
        [JsonPropertyName("prompt")]
        [Required]
        [Description("Text description of the video scene, subject, or action.")]
        public string Prompt { get; set; } = default!;

        [JsonPropertyName("num_frames")]
        [Range(18, 162)]
        [Description("Number of frames to generate (must be 12n+6).")]
        public int NumFrames { get; set; } = 78;

        [JsonPropertyName("enable_prompt_expansion")]
        [Description("Enable prompt expansion for richer generation.")]
        public bool EnablePromptExpansion { get; set; } = true;

        [JsonPropertyName("seed")]
        [Description("Optional seed for deterministic output.")]
        public int? Seed { get; set; }

        [JsonPropertyName("filename")]
        [Required]
        [Description("Output filename without extension.")]
        public string Filename { get; set; } = default!;
    }

    [Description("Transform an existing video using Krea WAN-14B (video-to-video). Upload or link a reference video and describe the desired transformation.")]
    [McpServerTool(
       Title = "Transform video with Krea WAN-14B (Video-to-Video)",
       Name = "aiml_video_krea_wan14b_v2v_generate",
       Destructive = false)]
    public static async Task<CallToolResult?> AIMLVideo_KreaWAN14BVideoToVideo(
       [Description("Prompt describing how to transform or modify the reference video.")] string prompt,
       [Description("Input video URL (SharePoint, OneDrive, or HTTPS).")] string videoUrl,
       IServiceProvider serviceProvider,
       RequestContext<CallToolRequestParams> requestContext,
       [Description("Denoising strength (0.0 keeps original, 1.0 fully regenerates). Default: 0.85"), Range(0.0, 1.0)] double strength = 0.85,
       [Description("Enable prompt expansion for richer results.")] bool enablePromptExpansion = true,
       [Description("Optional seed for deterministic results.")] int? seed = null,
       [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
       CancellationToken cancellationToken = default)
       => await requestContext.WithExceptionCheck(async () =>
   {
       var settings = serviceProvider.GetRequiredService<AIMLSettings>();
       var clientFactory = serviceProvider.GetRequiredService<IHttpClientFactory>();
       var downloadService = serviceProvider.GetRequiredService<DownloadService>();

       // Step 1: Download source video (if SharePoint/OneDrive or local)
       var files = await downloadService.DownloadContentAsync(serviceProvider, requestContext.Server, videoUrl, cancellationToken);
       var file = files.FirstOrDefault() ?? throw new Exception("Video file not found or could not be downloaded.");

       var dataUri = file.ToDataUri();

       // Step 3: Ask user for any missing input
       var (typed, notAccepted, _) = await requestContext.Server.TryElicit(
           new AIMLKreaWAN14BVideoToVideoRequest
           {
               Prompt = prompt,
               VideoUrl = videoUrl,
               Strength = strength,
               EnablePromptExpansion = enablePromptExpansion,
               Seed = seed,
               Filename = filename?.ToOutputFileName() ?? requestContext.ToOutputFileName("mp4")
           },
           cancellationToken);

       // Step 4: Build JSON payload
       var body = new
       {
           model = "krea/krea-wan-14b/video-to-video",
           prompt = typed.Prompt,
           video_url = dataUri,
           strength = typed.Strength,
           enable_prompt_expansion = typed.EnablePromptExpansion,
           seed = typed.Seed
       };

       var aiml = serviceProvider.GetRequiredService<AIMLClient>();
       var doc = await aiml.PostAsync(BASE_URL, body, cancellationToken);
       var id = doc.RootElement.TryGetProperty("id", out var idProp)
           ? idProp.GetString()
           : null;

       if (string.IsNullOrWhiteSpace(id))
           throw new Exception("No generation ID returned from Krea Video-to-Video API.");

       // Step 7: Return raw JSON + confirmation
       return doc.ToJsonContent(BASE_URL).ToCallToolResult();
   });

    // --- DTO ---

    [Description("Please fill in the Krea WAN-14B video-to-video generation request.")]
    public class AIMLKreaWAN14BVideoToVideoRequest
    {
        [JsonPropertyName("prompt")]
        [Required]
        [Description("Prompt describing how the reference video should be modified.")]
        public string Prompt { get; set; } = default!;

        [JsonPropertyName("video_url")]
        [Required]
        [Description("HTTPS or SharePoint/OneDrive link to the source video.")]
        public string VideoUrl { get; set; } = default!;

        [JsonPropertyName("strength")]
        [Range(0.0, 1.0)]
        [Description("Denoising strength (0 = original, 1 = full regeneration).")]
        public double Strength { get; set; } = 0.85;

        [JsonPropertyName("enable_prompt_expansion")]
        [Description("Enable prompt expansion for richer results.")]
        public bool EnablePromptExpansion { get; set; } = true;

        [JsonPropertyName("seed")]
        [Description("Optional seed for deterministic output.")]
        public int? Seed { get; set; }

        [JsonPropertyName("filename")]
        [Required]
        [Description("Output filename without extension.")]
        public string Filename { get; set; } = default!;
    }


    private static readonly string RUNWAY_URL = "https://api.aimlapi.com/v2/generate/video/runway/generation";

    [Description("Transform a video using Runway Gen-4 Aleph. Provide a video and a prompt describing the desired transformation. The input video will be base64-encoded automatically.")]
    [McpServerTool(
        Title = "Transform video with Runway Gen-4 Aleph",
        Name = "aiml_video_runway_gen4aleph_generate",
        Destructive = false)]
    public static async Task<CallToolResult?> AIMLVideo_RunwayGen4AlephGenerate(
        [Description("Prompt describing the desired transformation of the input video.")] string prompt,
        [Description("Input video URL (SharePoint, OneDrive, or HTTPS).")] string videoUrl,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Output duration in seconds. Default: 5")] RunwayDuration duration = RunwayDuration.Seconds5,
        [Description("Output frame size. Default: 1280:720")] RunwayFrameSize frameSize = RunwayFrameSize.Size1280x720,
        [Description("Optional seed for deterministic generation.")] uint? seed = null,
        [Description("Optional image references influencing style or content.")] List<RunwayReference>? references = null,
        [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
    {
        var settings = serviceProvider.GetRequiredService<AIMLSettings>();
        var clientFactory = serviceProvider.GetRequiredService<IHttpClientFactory>();
        var downloadService = serviceProvider.GetRequiredService<DownloadService>();
        var aiml = serviceProvider.GetRequiredService<AIMLClient>();

        // Step 1: Download and encode input video
        var files = await downloadService.DownloadContentAsync(serviceProvider, requestContext.Server, videoUrl, cancellationToken);
        var file = files.FirstOrDefault() ?? throw new Exception("Video file not found or could not be downloaded.");
        var base64 = Convert.ToBase64String(file.Contents.ToArray());
        var dataUri = $"data:video/mp4;base64,{base64}";

        // Step 2: Build JSON body (no elicitation for video input)
        var body = new
        {
            model = "runway/gen4_aleph",
            video_url = dataUri,
            prompt,
            duration = (int)duration,
            frame_size = frameSize.GetEnumMemberValue(),
            seed,
            references
        };

        // Step 3: Send request
        var doc = await aiml.PostAsync(RUNWAY_URL, body, cancellationToken);
        var id = doc.RootElement.TryGetProperty("id", out var idProp)
            ? idProp.GetString()
            : null;
        if (string.IsNullOrWhiteSpace(id))
            throw new Exception("No generation ID returned from Runway API.");

        return doc.ToJsonContent(RUNWAY_URL).ToCallToolResult();
    });

    // --- DTOs & Enums ---

    [Description("Reference object for Runway video generation.")]
    public class RunwayReference
    {
        [JsonPropertyName("type")]
        [Description("Reference type, e.g., 'image'.")]
        public string Type { get; set; } = "image";

        [JsonPropertyName("url")]
        [Description("HTTPS URL to the reference image.")]
        public string Url { get; set; } = default!;
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum RunwayDuration
    {
        [EnumMember(Value = "5")]
        Seconds5 = 5
    }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum RunwayFrameSize
    {
        [EnumMember(Value = "1280:720")]
        Size1280x720,
        [EnumMember(Value = "720:1280")]
        Size720x1280,
        [EnumMember(Value = "1104:832")]
        Size1104x832,
        [EnumMember(Value = "832:1104")]
        Size832x1104,
        [EnumMember(Value = "960:960")]
        Size960x960,
        [EnumMember(Value = "1584:672")]
        Size1584x672,
        [EnumMember(Value = "848:480")]
        Size848x480,
        [EnumMember(Value = "640:480")]
        Size640x480
    }

    //private static readonly string STATUS_URL = "https://api.aimlapi.com/v2/generate/video/runway/generation";
    // ─────────────────────────────────────────────────────────────
    // TOOL: Check the status of a video generation by ID
    // ─────────────────────────────────────────────────────────────
    /*  [Description("Check the status of an AI/ML video generation by ID. If completed, the video is uploaded and returned as a link.")]
      [McpServerTool(
          Title = "Check AI/ML video generation status",
          Name = "aiml_video_check_status",
          Destructive = false,
          ReadOnly = false)]
      public static async Task<CallToolResult?> AIMLVideo_CheckStatusAndUpload(
          [Description("The video generation ID returned by the API.")] string generationId,
          IServiceProvider serviceProvider,
          RequestContext<CallToolRequestParams> requestContext,
          [Description("Optional output filename (without extension). Defaults to generation ID.")] string? filename = null,
          [Description("If true, the tool waits until the generation is completed before returning. Default: false.")] bool waitUntilCompleted = false,
          [Description("Optional polling interval in seconds (default 10).")] int checkIntervalSeconds = 10,
          CancellationToken cancellationToken = default)
          => await requestContext.WithExceptionCheck(async () =>
      {
          return await CheckAndUploadAsync(
              serviceProvider,
              requestContext,
              generationId,
              filename,
              waitUntilCompleted,
              TimeSpan.FromSeconds(checkIntervalSeconds),
              cancellationToken: cancellationToken);
      });

    public static async Task<CallToolResult> CheckAndUploadAsync(
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        string generationId,
        string? filename = null,
        bool waitUntilCompleted = false,
        TimeSpan? checkInterval = null,
        string? generationUrl = "https://api.aimlapi.com/v2/video/generations",
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNullOrWhiteSpace(generationId);

        var settings = serviceProvider.GetRequiredService<AIMLSettings>();
        var clientFactory = serviceProvider.GetRequiredService<IHttpClientFactory>();
        var downloadService = serviceProvider.GetRequiredService<DownloadService>();
        using var client = clientFactory.CreateClient();

        checkInterval ??= TimeSpan.FromSeconds(10);

        // Internal helper: query current generation status
        async Task<(string status, List<string> urls, JsonDocument doc)> QueryStatusAsync()
        {
            var uri = $"{generationUrl}?generation_id={generationId}";
            using var req = new HttpRequestMessage(HttpMethod.Get, uri);
            req.Headers.Authorization = new AuthenticationHeaderValue("Bearer", settings.ApiKey);
            req.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            using var resp = await client.SendAsync(req, cancellationToken);
            var json = await resp.Content.ReadAsStringAsync(cancellationToken);
            if (!resp.IsSuccessStatusCode)
                throw new Exception($"{resp.StatusCode}: {json}");

            var doc = JsonDocument.Parse(json);
            var root = doc.RootElement;

            var status = root.TryGetProperty("status", out var statusProp)
                ? statusProp.GetString() ?? "unknown"
                : "unknown";

            var urls = root.TryGetProperty("video", out var arr) && arr.ValueKind == JsonValueKind.Array
                ? arr.EnumerateArray().Select(x => x.GetString()!).Where(x => !string.IsNullOrWhiteSpace(x)).ToList()
                : [];

            return (status, urls, doc);
        }

        // ── Polling loop ──
        (string status, List<string> urls, JsonDocument doc) result;
        do
        {
            result = await QueryStatusAsync();

            if (!waitUntilCompleted || string.Equals(result.status, "completed", StringComparison.OrdinalIgnoreCase))
                break;

            await Task.Delay(checkInterval.Value, cancellationToken);
        }
        while (!cancellationToken.IsCancellationRequested);

        // ── Not yet complete → return status only ──
        if (!string.Equals(result.status, "completed", StringComparison.OrdinalIgnoreCase))
        {
            return new CallToolResult
            {
                Content =
                [
                    result.doc.ToJsonContent(generationUrl!),
                    $"⌛ Generation `{generationId}` is **{result.status}**. Please check again later.".ToTextContentBlock()
                ]
            };
        }

        // ── Completed → download + upload ──
        if (result.urls.Count == 0)
            throw new Exception("No video URLs found in completed response.");

        var videoUrl = result.urls.First();
        var files = await downloadService.DownloadContentAsync(serviceProvider, requestContext.Server, videoUrl, cancellationToken);
        var file = files.FirstOrDefault() ?? throw new Exception("Unable to download video file.");

        var finalName = $"{(string.IsNullOrWhiteSpace(filename) ? generationId : filename)}.mp4";
        var uploaded = await requestContext.Server.Upload(
            serviceProvider,
            finalName,
            BinaryData.FromBytes(file.Contents.ToArray()),
            cancellationToken);

        // ── Return final link ──
        return new CallToolResult
        {
            Content =
            [
                result.doc.ToJsonContent(generationUrl!),
                uploaded!
            ]
        };
    }*/


}