using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Net.Http.Headers;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using MCPhappey.Common.Extensions;
using MCPhappey.Core.Extensions;
using MCPhappey.Core.Services;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.KernelMemory.Pipeline;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;

namespace MCPhappey.Tools.AIML.Video;

public static partial class AIMLVideo
{
  /*  [Description("Generate a smooth AI video transition between two images using Google Veo 3.1 Fast (first-to-last image-to-video). Ideal for morphing or cinematic transformations.")]
    [McpServerTool(
       Title = "Generate video (First → Last Image) with Google Veo 3.1 Fast",
       Name = "aiml_video_google_veo31fast_firstlast_generate",
       Destructive = false)]
    public static async Task<CallToolResult?> AIMLVideo_GoogleVeo31FastFirstLastGenerate(
       [Description("Prompt describing the visual story or transition between the first and last image."), MaxLength(4000)] string prompt,
       [Description("URL of the first input image (at least 720p).")] string imageUrl,
       [Description("URL or Base64 string of the final image to morph into.")] string lastImageUrl,
       IServiceProvider serviceProvider,
       RequestContext<CallToolRequestParams> requestContext,
       [Description("Aspect ratio of the generated video. Default: 16:9")] VeoAspectRatio aspectRatio = VeoAspectRatio.Ratio_16x9,
       [Description("Duration of the video in seconds. Only 8 supported.")] int duration = 8,
       [Description("Video resolution (720p or 1080p). Default: 1080p")] VeoResolution resolution = VeoResolution.p1080,
       [Description("Generate audio for the video. Default: true")] bool generateAudio = true,
       [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
       [Description("If true, the tool waits until the generation is completed before returning.")] bool waitUntilCompleted = false,
       CancellationToken cancellationToken = default)
       => await requestContext.WithExceptionCheck(async () =>
   {
       var settings = serviceProvider.GetRequiredService<AIMLSettings>();
       var clientFactory = serviceProvider.GetRequiredService<IHttpClientFactory>();

       // Step 1: Ask user for any missing input
       var (typed, notAccepted, _) = await requestContext.Server.TryElicit(
           new AIMLVeo31FastFirstLastRequest
           {
               Prompt = prompt,
               AspectRatio = aspectRatio,
               Duration = duration,
               Resolution = resolution,
               GenerateAudio = generateAudio,
               Filename = filename?.ToOutputFileName() ?? requestContext.ToOutputFileName("mp4")
           },
           cancellationToken);
       var downloadService = serviceProvider.GetRequiredService<DownloadService>();
       var files = await downloadService.DownloadContentAsync(serviceProvider, requestContext.Server, imageUrl, cancellationToken);
       var bytes = files.FirstOrDefault() ?? throw new Exception($"Failed to download image: {imageUrl}");

       var lastFiles = await downloadService.DownloadContentAsync(serviceProvider, requestContext.Server, lastImageUrl, cancellationToken);
       var lastBytes = files.FirstOrDefault() ?? throw new Exception($"Failed to download image: {imageUrl}");

       // Step 2: Build JSON payload
       var body = new
       {
           model = "google/veo-3.1-first-last-image-to-video-fast",
           prompt = typed.Prompt,
           image_url = bytes.ToDataUri(),
           last_image_url = lastBytes.ToDataUri(),
           aspect_ratio = typed.AspectRatio.GetEnumMemberValue(),
           duration = (int)typed.Duration,
           resolution = typed.Resolution.GetEnumMemberValue(),
           generate_audio = typed.GenerateAudio
       };

       var aiml = serviceProvider.GetRequiredService<AIMLClient>();
       var doc = await aiml.PostAsync(BASE_URL, body, cancellationToken);

       var id = doc.RootElement.TryGetProperty("id", out var idProp)
           ? idProp.GetString()
           : null;

       if (string.IsNullOrWhiteSpace(id))
           throw new Exception("No generation ID returned from Google Veo 3.1 First/Last API.");

       if (waitUntilCompleted)
       {
           return await CheckAndUploadAsync(
               serviceProvider,
               requestContext,
               id.Split(":").First(),
               filename,
               waitUntilCompleted: true,
               cancellationToken: cancellationToken);
       }

       return new CallToolResult()
       {
           Content =
           [
               doc.ToJsonContent($"{BASE_URL}/v2/video/generations")
           ]
       };
   });
*/
    private static async Task<CallToolResult> CheckAndUploadAsync(
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        string generationId,
        string? filename = null,
        bool waitUntilCompleted = false,
        TimeSpan? checkInterval = null,
        CancellationToken cancellationToken = default)
    {
        var settings = serviceProvider.GetRequiredService<AIMLSettings>();
        var clientFactory = serviceProvider.GetRequiredService<IHttpClientFactory>();
        var downloadService = serviceProvider.GetRequiredService<DownloadService>();
        using var client = clientFactory.CreateClient();

        checkInterval ??= TimeSpan.FromSeconds(10);

        var uri = $"https://api.aimlapi.com/v2/video/generations?generation_id={generationId}";

        // Internal helper: query current generation status
        async Task<(string status, string? url, JsonDocument doc)> QueryStatusAsync()
        {
            using var req = new HttpRequestMessage(HttpMethod.Get, uri);
            req.Headers.Authorization = new AuthenticationHeaderValue("Bearer", settings.ApiKey);
            req.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            using var resp = await client.SendAsync(req, cancellationToken);
            var json = await resp.Content.ReadAsStringAsync(cancellationToken);
            if (!resp.IsSuccessStatusCode)
                throw new Exception($"{resp.StatusCode}: {json}");

            var doc = JsonDocument.Parse(json);
            var root = doc.RootElement;

            var status = root.TryGetProperty("status", out var statusProp)
                ? statusProp.GetString() ?? "unknown"
                : "unknown";

            var url = root.TryGetProperty("video", out var videoElem)
                    && videoElem.ValueKind == JsonValueKind.Object
                    && videoElem.TryGetProperty("url", out var urlElem)
                    ? urlElem.GetString()
                    : null;

            return (status, url, doc);
        }

        // ── Polling loop ──
        (string status, string? url, JsonDocument doc) result;
        do
        {
            result = await QueryStatusAsync();

            if (!waitUntilCompleted || string.Equals(result.status, "completed", StringComparison.OrdinalIgnoreCase))
                break;

            await Task.Delay(checkInterval.Value, cancellationToken);
        }
        while (!cancellationToken.IsCancellationRequested);

        // ── Not yet complete → return status only ──
        if (!string.Equals(result.status, "completed", StringComparison.OrdinalIgnoreCase))
        {
            return new CallToolResult
            {
                Content =
                [
                    result.doc.ToJsonContent(uri!),
                    $"⌛ Generation `{generationId}` is **{result.status}**. Please check again later.".ToTextContentBlock()
                ]
            };
        }

        // ── Completed → download + upload ──

        var videoUrl = result.url!;
        var files = await downloadService.DownloadContentAsync(serviceProvider, requestContext.Server, videoUrl, cancellationToken);
        var file = files.FirstOrDefault() ?? throw new Exception("Unable to download video file.");

        var finalName = $"{(string.IsNullOrWhiteSpace(filename) ? generationId : filename)}.mp4";
        var uploaded = await requestContext.Server.Upload(
            serviceProvider,
            finalName,
            BinaryData.FromBytes(file.Contents.ToArray()),
            cancellationToken);

        // ── Return final link ──
        return new CallToolResult
        {
            Content =
            [
                result.doc.ToJsonContent(uri!),
                uploaded!
            ]
        };
    }

    [Description("Generate a high-quality AI video using Google Veo 3.1 (text-to-video). Includes prompt enhancement, audio generation, and auto-fix features.")]
    [McpServerTool(
        Title = "Generate video with Google Veo 3.1",
        Name = "aiml_video_google_veo31_generate",
        Destructive = false)]
    public static async Task<CallToolResult?> AIMLVideo_GoogleVeo31Generate(
        [Description("Prompt describing the video content (scene, subject, or action)."), MaxLength(4000)] string prompt,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Aspect ratio of the generated video. Default: 16:9")] VeoAspectRatio aspectRatio = VeoAspectRatio.Ratio_16x9,
        [Description("Duration of the video in seconds (4, 6 or 8).")] int duration = 8,
        [Description("Video resolution (720p or 1080p). Default: 1080p")] VeoResolution resolution = VeoResolution.p1080,
        [Description("Optional description of what to avoid in the video.")] string? negativePrompt = null,
        [Description("Enable prompt enhancement using AI. Default: true")] bool enhancePrompt = true,
        [Description("Generate audio with the video. Default: true")] bool generateAudio = true,
        [Description("Enable automatic fixing of problematic prompts. Default: true")] bool autoFix = true,
        [Description("Optional seed for deterministic generation.")] int? seed = null,
        [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
        [Description("If true, the tool waits until the generation is completed before returning.")] bool waitUntilCompleted = false,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
    {
        var settings = serviceProvider.GetRequiredService<AIMLSettings>();
        var clientFactory = serviceProvider.GetRequiredService<IHttpClientFactory>();
        var aiml = serviceProvider.GetRequiredService<AIMLClient>();

        // Step 1: Ask user for missing input
        var (typed, notAccepted, _) = await requestContext.Server.TryElicit(
            new AIMLVeo31VideoRequest
            {
                Prompt = prompt,
                AspectRatio = aspectRatio,
                Duration = duration,
                Resolution = resolution,
                NegativePrompt = negativePrompt,
                EnhancePrompt = enhancePrompt,
                GenerateAudio = generateAudio,
                AutoFix = autoFix,
                Seed = seed,
                Filename = filename?.ToOutputFileName() ?? requestContext.ToOutputFileName("mp4")
            },
            cancellationToken);

        // Step 2: Build JSON payload
        var body = new
        {
            model = "google/veo-3.1-t2v",
            prompt = typed.Prompt,
            aspect_ratio = typed.AspectRatio.GetEnumMemberValue(),
            duration = (int)typed.Duration,
            resolution = typed.Resolution.GetEnumMemberValue(),
            negative_prompt = typed.NegativePrompt,
            enhance_prompt = typed.EnhancePrompt,
            generate_audio = typed.GenerateAudio,
            seed = typed.Seed,
            auto_fix = typed.AutoFix
        };

        var doc = await aiml.PostAsync(BASE_URL, body, cancellationToken);
        var id = doc.RootElement.TryGetProperty("id", out var idProp)
            ? idProp.GetString()
            : null;

        if (string.IsNullOrWhiteSpace(id))
            throw new Exception("No generation ID returned from Google Veo API.");

        if (waitUntilCompleted)
        {
            return await CheckAndUploadAsync(
                serviceProvider,
                requestContext,
                id.Split(":").First(),
                filename,
                waitUntilCompleted: true,
                cancellationToken: cancellationToken);
        }

        // Step 5: Return raw JSON + user info
        return doc.ToJsonContent(BASE_URL).ToCallToolResult();
    });


    [Description("Generate a fast AI video using Google Veo 3.1 Fast (text-to-video). Same quality as Veo 3.1 but optimized for faster inference.")]
    [McpServerTool(
       Title = "Generate video with Google Veo 3.1 Fast",
       Name = "aiml_video_google_veo31fast_generate",
       Destructive = false)]
    public static async Task<CallToolResult?> AIMLVideo_GoogleVeo31FastGenerate(
       [Description("Prompt describing the video content (scene, subject, or action)."), MaxLength(4000)] string prompt,
       IServiceProvider serviceProvider,
       RequestContext<CallToolRequestParams> requestContext,
       [Description("Aspect ratio of the generated video. Default: 16:9")] VeoAspectRatio aspectRatio = VeoAspectRatio.Ratio_16x9,
       [Description("Duration of the video in seconds (4, 6 or 8).")] int duration = 8,
       [Description("Video resolution (720p or 1080p). Default: 1080p")] VeoResolution resolution = VeoResolution.p1080,
       [Description("Optional description of what to avoid in the video.")] string? negativePrompt = null,
       [Description("Enable prompt enhancement using AI. Default: true")] bool enhancePrompt = true,
       [Description("Generate audio with the video. Default: true")] bool generateAudio = true,
       [Description("Enable automatic fixing of problematic prompts. Default: true")] bool autoFix = true,
       [Description("Optional seed for deterministic generation.")] int? seed = null,
       [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
       CancellationToken cancellationToken = default)
       => await requestContext.WithExceptionCheck(async () =>
   {
       var settings = serviceProvider.GetRequiredService<AIMLSettings>();
       var clientFactory = serviceProvider.GetRequiredService<IHttpClientFactory>();

       // Step 1: ask user for any missing input
       var (typed, notAccepted, _) = await requestContext.Server.TryElicit(
           new AIMLVeo31FastVideoRequest
           {
               Prompt = prompt,
               AspectRatio = aspectRatio,
               Duration = duration,
               Resolution = resolution,
               NegativePrompt = negativePrompt,
               EnhancePrompt = enhancePrompt,
               GenerateAudio = generateAudio,
               AutoFix = autoFix,
               Seed = seed,
               Filename = filename?.ToOutputFileName() ?? requestContext.ToOutputFileName("mp4")
           },
           cancellationToken);

       // Step 2: build JSON payload
       var jsonBody = JsonSerializer.Serialize(new
       {
           model = "google/veo-3.1-t2v-fast",
           prompt = typed.Prompt,
           aspect_ratio = typed.AspectRatio.GetEnumMemberValue(),
           duration = (int)typed.Duration,
           resolution = typed.Resolution.GetEnumMemberValue(),
           negative_prompt = typed.NegativePrompt,
           enhance_prompt = typed.EnhancePrompt,
           generate_audio = typed.GenerateAudio,
           seed = typed.Seed,
           auto_fix = typed.AutoFix
       });

       using var client = clientFactory.CreateClient();
       using var request = new HttpRequestMessage(HttpMethod.Post, BASE_URL);
       request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", settings.ApiKey);
       request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(MimeTypes.Json));
       request.Content = new StringContent(jsonBody, Encoding.UTF8, MimeTypes.Json);

       // Step 3: send request
       using var resp = await client.SendAsync(request, cancellationToken);
       var jsonResponse = await resp.Content.ReadAsStringAsync(cancellationToken);
       if (!resp.IsSuccessStatusCode)
           throw new Exception($"{resp.StatusCode}: {jsonResponse}");

       // Step 4: parse response
       using var doc = JsonDocument.Parse(jsonResponse);
       var id = doc.RootElement.TryGetProperty("id", out var idProp)
           ? idProp.GetString()
           : null;

       if (string.IsNullOrWhiteSpace(id))
           throw new Exception("No generation ID returned from Google Veo Fast API.");

       // Step 5: return JSON + info
       return new CallToolResult()
       {
           Content =
           [
                doc.ToJsonContent(BASE_URL),
                $"⚡ Google Veo 3.1 Fast video generation started (ID: {id}). Processing asynchronously.".ToTextContentBlock()
           ]
       };
   });

    // --- DTO & Enums ---

    [Description("Please fill in the Google Veo 3.1 Fast video generation request.")]
    public class AIMLVeo31FastVideoRequest
    {
        [JsonPropertyName("prompt")]
        [Required]
        [Description("Text description of the video scene or action.")]
        public string Prompt { get; set; } = default!;

        [JsonPropertyName("aspect_ratio")]
        [Required]
        public VeoAspectRatio AspectRatio { get; set; } = VeoAspectRatio.Ratio_16x9;

        [JsonPropertyName("duration")]
        [Required]
        public int Duration { get; set; } = 8;

        [JsonPropertyName("resolution")]
        [Required]
        public VeoResolution Resolution { get; set; } = VeoResolution.p1080;

        [JsonPropertyName("negative_prompt")]
        public string? NegativePrompt { get; set; }

        [JsonPropertyName("enhance_prompt")]
        public bool EnhancePrompt { get; set; } = true;

        [JsonPropertyName("generate_audio")]
        public bool GenerateAudio { get; set; } = true;

        [JsonPropertyName("auto_fix")]
        public bool AutoFix { get; set; } = true;

        [JsonPropertyName("seed")]
        public int? Seed { get; set; }

        [JsonPropertyName("filename")]
        [Required]
        public string Filename { get; set; } = default!;
    }


}



// --- DTO ---

[Description("Please fill in the Google Veo 3.1 Fast First/Last video generation request.")]
public class AIMLVeo31FastFirstLastRequest
{
    [JsonPropertyName("prompt")]
    [Required]
    [Description("Text prompt describing the visual transition or story.")]
    public string Prompt { get; set; } = default!;

    [JsonPropertyName("aspect_ratio")]
    [Required]
    [Description("Aspect ratio of the generated video.")]
    public VeoAspectRatio AspectRatio { get; set; } = VeoAspectRatio.Ratio_16x9;

    [JsonPropertyName("duration")]
    [Required]
    [Description("Duration in seconds (only 8 supported).")]
    public int Duration { get; set; } = 8;

    [JsonPropertyName("resolution")]
    [Required]
    [Description("Video resolution (720p or 1080p).")]
    public VeoResolution Resolution { get; set; } = VeoResolution.p1080;

    [JsonPropertyName("generate_audio")]
    [Description("Generate audio along with the video.")]
    public bool GenerateAudio { get; set; } = true;

    [JsonPropertyName("filename")]
    [Required]
    [Description("Output filename without extension.")]
    public string Filename { get; set; } = default!;
}


[JsonConverter(typeof(JsonStringEnumConverter))]
public enum VeoAspectRatio
{
    [EnumMember(Value = "16:9")]
    Ratio_16x9,
    [EnumMember(Value = "9:16")]
    Ratio_9x16,
    [EnumMember(Value = "1:1")]
    Ratio_1x1
}


// --- DTOs & Enums ---

[Description("Please fill in the Google Veo 3.1 video generation request.")]
public class AIMLVeo31VideoRequest
{
    [JsonPropertyName("prompt")]
    [Required]
    [Description("Text description of the desired video scene or action.")]
    public string Prompt { get; set; } = default!;

    [JsonPropertyName("aspect_ratio")]
    [Required]
    [Description("Aspect ratio of the video.")]
    public VeoAspectRatio AspectRatio { get; set; } = VeoAspectRatio.Ratio_16x9;

    [JsonPropertyName("duration")]
    [Required]
    [Description("Video duration in seconds.")]
    public int Duration { get; set; } = 8;

    [JsonPropertyName("resolution")]
    [Required]
    [Description("Video resolution (720p or 1080p).")]
    public VeoResolution Resolution { get; set; } = VeoResolution.p1080;

    [JsonPropertyName("negative_prompt")]
    [Description("Elements to exclude from the generated video.")]
    public string? NegativePrompt { get; set; }

    [JsonPropertyName("enhance_prompt")]
    [Description("Whether to enhance the prompt using AI.")]
    public bool EnhancePrompt { get; set; } = true;

    [JsonPropertyName("generate_audio")]
    [Description("Generate audio along with video.")]
    public bool GenerateAudio { get; set; } = true;

    [JsonPropertyName("auto_fix")]
    [Description("Automatically fix invalid or blocked prompts.")]
    public bool AutoFix { get; set; } = true;

    [JsonPropertyName("seed")]
    [Description("Optional seed for deterministic output.")]
    public int? Seed { get; set; }

    [JsonPropertyName("filename")]
    [Required]
    [Description("Output filename without extension.")]
    public string Filename { get; set; } = default!;
}


[JsonConverter(typeof(JsonStringEnumConverter))]
public enum VeoResolution
{
    [EnumMember(Value = "720p")]
    p720,
    [EnumMember(Value = "1080p")]
    p1080
}
