using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using MCPhappey.Common.Extensions;
using MCPhappey.Core.Extensions;
using MCPhappey.Core.Services;
using Microsoft.Extensions.DependencyInjection;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;

namespace MCPhappey.Tools.ZAI;

public static class ZAIImages
{
    [Description("Generate image(s) with Z.AI, upload outputs to SharePoint/OneDrive, and return only resource link blocks.")]
    [McpServerTool(Title = "Generate images with Z.AI", Name = "zai_images_generate", Destructive = false, OpenWorld = true)]
    public static async Task<CallToolResult?> ZAI_Images_Generate(
        [Description("Prompt text describing the image to generate.")] string prompt,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Model code. Supported values: glm-image, cogview-4-250304.")] string model = "glm-image",
        [Description("Image quality. Supported values: hd, standard.")] string quality = "hd",
        [Description("Image size, e.g. 1280x1280.")] string size = "1280x1280",
        [Description("Unique end-user ID for abuse monitoring (6-128 chars). Optional.")] string? userId = null,
        [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
    {
        var (typed, notAccepted, _) = await requestContext.Server.TryElicit(
            new ZAIImageGenerateRequest
            {
                Prompt = prompt,
                Model = model,
                Quality = quality,
                Size = size,
                UserId = userId,
                Filename = filename
            },
            cancellationToken);

        if (string.IsNullOrWhiteSpace(typed.Prompt))
            throw new ValidationException("prompt is required.");

        if (!string.Equals(typed.Model, "glm-image", StringComparison.OrdinalIgnoreCase)
            && !string.Equals(typed.Model, "cogview-4-250304", StringComparison.OrdinalIgnoreCase))
            throw new ValidationException("model must be one of: glm-image, cogview-4-250304.");

        if (!string.Equals(typed.Quality, "hd", StringComparison.OrdinalIgnoreCase)
            && !string.Equals(typed.Quality, "standard", StringComparison.OrdinalIgnoreCase))
            throw new ValidationException("quality must be one of: hd, standard.");

        if (!string.IsNullOrWhiteSpace(typed.UserId) && (typed.UserId.Length < 6 || typed.UserId.Length > 128))
            throw new ValidationException("userId must be 6 to 128 characters when provided.");

        var client = serviceProvider.GetRequiredService<ZAIClient>();
        var body = new
        {
            model = typed.Model,
            prompt = typed.Prompt,
            quality = typed.Quality,
            size = typed.Size,
            user_id = typed.UserId
        };

        JsonNode? response = await client.PostAsync("paas/v4/images/generations", body, null, cancellationToken);
        var data = response?["data"]?.AsArray() ?? throw new Exception("No image data returned from Z.AI.");
        if (data.Count == 0)
            throw new Exception("No image data returned from Z.AI.");

        var downloadService = serviceProvider.GetRequiredService<DownloadService>();
        var links = new List<ResourceLinkBlock>();
        var baseName = typed.Filename?.ToOutputFileName() ?? requestContext.ToOutputFileName();

        var i = 0;
        foreach (var item in data)
        {
            i++;
            var url = item?["url"]?.GetValue<string>();
            if (string.IsNullOrWhiteSpace(url))
                continue;

            var files = await downloadService.DownloadContentAsync(serviceProvider, requestContext.Server, url, cancellationToken);
            var file = files.FirstOrDefault();
            if (file == null)
                continue;

            var ext = GetImageExtension(file.Filename, file.MimeType);
            var uploaded = await requestContext.Server.Upload(
                serviceProvider,
                $"{baseName}-{i}{ext}",
                BinaryData.FromBytes(file.Contents.ToArray()),
                cancellationToken);

            if (uploaded != null)
                links.Add(uploaded);
        }

        if (links.Count == 0)
            throw new Exception("Image generation succeeded but no outputs could be uploaded.");

        return links.ToResourceLinkCallToolResponse();
    });

    private static string GetImageExtension(string? filename, string? mimeType)
    {
        var ext = Path.GetExtension(filename ?? string.Empty);
        if (!string.IsNullOrWhiteSpace(ext))
            return ext;

        return mimeType?.ToLowerInvariant() switch
        {
            "image/jpeg" => ".jpg",
            "image/webp" => ".webp",
            "image/gif" => ".gif",
            "image/bmp" => ".bmp",
            _ => ".png"
        };
    }
}

[Description("Please confirm the Z.AI image generation request.")]
public class ZAIImageGenerateRequest
{
    [JsonPropertyName("model")]
    [Required]
    [Description("Model code: glm-image or cogview-4-250304.")]
    public string Model { get; set; } = "glm-image";

    [JsonPropertyName("prompt")]
    [Required]
    [Description("Text description of the image to generate.")]
    public string Prompt { get; set; } = default!;

    [JsonPropertyName("quality")]
    [Description("Image quality: hd or standard.")]
    public string Quality { get; set; } = "hd";

    [JsonPropertyName("size")]
    [Description("Image size, e.g. 1280x1280.")]
    public string Size { get; set; } = "1280x1280";

    [JsonPropertyName("userId")]
    [Description("Optional unique end-user ID for abuse monitoring (6-128 chars).")]
    public string? UserId { get; set; }

    [JsonPropertyName("filename")]
    [Description("Output filename without extension.")]
    public string? Filename { get; set; }
}

