using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Net.Http.Headers;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using MCPhappey.Common.Extensions;
using MCPhappey.Core.Extensions;
using MCPhappey.Core.Services;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.KernelMemory.Pipeline;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;

namespace MCPhappey.Tools.Fireworks;

public static class FireworksImages
{
    private const string FluxSchnellUrl = "https://api.fireworks.ai/inference/v1/workflows/accounts/fireworks/models/flux-1-schnell-fp8/text_to_image";

    [Description("Generate images with Fireworks FLUX.1 schnell, confirm via elicitation, upload outputs to SharePoint/OneDrive, and return structured content plus resource links.")]
    [McpServerTool(
        Title = "Fireworks FLUX.1 schnell image generation",
        Name = "fireworks_flux_schnell_generate",
        Destructive = false,
        OpenWorld = true)]
    public static async Task<CallToolResult?> Fireworks_FluxSchnell_Generate(
        [Description("Prompt describing the image to generate.")] string prompt,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Aspect ratio (e.g., 1:1, 16:9, 9:16). Default: 16:9.")] string aspectRatio = "16:9",
        [Description("Guidance scale. Default: 3.5.")] double guidanceScale = 3.5,
        [Description("Number of inference steps. Default: 4.")] int numInferenceSteps = 4,
        [Description("Seed for reproducibility (0 = random). Default: 0.")] int seed = 0,
        [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
            await requestContext.WithStructuredContent(async () =>
            {
                var (typed, notAccepted, _) = await requestContext.Server.TryElicit(
                    new FireworksFluxSchnellRequest
                    {
                        Prompt = prompt,
                        AspectRatio = aspectRatio,
                        GuidanceScale = guidanceScale,
                        NumInferenceSteps = numInferenceSteps,
                        Seed = seed,
                        Filename = filename?.ToOutputFileName() ?? requestContext.ToOutputFileName()
                    },
                    cancellationToken);

                if (notAccepted != null) return notAccepted;
                if (typed == null) return "No input data provided".ToErrorCallToolResponse();

                ValidateSchnellRequest(typed);

                var settings = serviceProvider.GetRequiredService<FireworksSettings>();
                var clientFactory = serviceProvider.GetRequiredService<IHttpClientFactory>();
                var downloadService = serviceProvider.GetRequiredService<DownloadService>();

                var payload = new JsonObject
                {
                    ["prompt"] = typed.Prompt,
                    ["aspect_ratio"] = typed.AspectRatio,
                    ["guidance_scale"] = typed.GuidanceScale,
                    ["num_inference_steps"] = typed.NumInferenceSteps,
                    ["seed"] = typed.Seed
                };

                using var client = clientFactory.CreateClient();
                using var req = new HttpRequestMessage(HttpMethod.Post, FluxSchnellUrl)
                {
                    Content = new StringContent(payload.ToJsonString(), System.Text.Encoding.UTF8, MimeTypes.Json)
                };

                req.Headers.Authorization = new AuthenticationHeaderValue("Bearer", settings.ApiKey);
                req.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(MimeTypes.Json));

                using var resp = await client.SendAsync(req, cancellationToken);
                var body = await resp.Content.ReadAsStringAsync(cancellationToken);

                if (!resp.IsSuccessStatusCode)
                    throw new InvalidOperationException($"Fireworks image generation failed ({(int)resp.StatusCode}): {body}");

                var json = JsonNode.Parse(body) as JsonObject ?? new JsonObject();
                var base64Array = json["base64"]?.AsArray() ?? new JsonArray();

                if (base64Array.Count == 0)
                    throw new InvalidOperationException("Fireworks returned no base64 image data.");

                var links = new List<ResourceLinkBlock>();
                var index = 0;
                foreach (var item in base64Array)
                {
                    index++;
                    var dataUrl = item?.GetValue<string>();
                    if (string.IsNullOrWhiteSpace(dataUrl))
                        continue;

                    var bytes = DecodeDataUrlToBytes(dataUrl);
                    if (bytes == null || bytes.Length == 0)
                        continue;

                    var outputName = BuildImageName(typed.Filename, index, ".png");
                    var uploaded = await requestContext.Server.Upload(
                        serviceProvider,
                        outputName,
                        BinaryData.FromBytes(bytes),
                        cancellationToken);

                    if (uploaded != null)
                        links.Add(uploaded);
                }

                if (links.Count == 0)
                    throw new InvalidOperationException("Image generation succeeded but no outputs could be uploaded.");

                return new CallToolResult
                {
                    StructuredContent = json,
                    Content = [.. links]
                };
            }));

    private static void ValidateSchnellRequest(FireworksFluxSchnellRequest typed)
    {
        if (string.IsNullOrWhiteSpace(typed.Prompt))
            throw new ValidationException("prompt is required.");

        var allowedRatios = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "1:1","21:9","16:9","3:2","5:4","4:5","2:3","9:16","9:21","4:3","3:4"
        };

        if (!allowedRatios.Contains(typed.AspectRatio))
            throw new ValidationException("aspectRatio must be one of: 1:1, 21:9, 16:9, 3:2, 5:4, 4:5, 2:3, 9:16, 9:21, 4:3, 3:4.");

        if (typed.GuidanceScale < 0)
            throw new ValidationException("guidanceScale must be >= 0.");

        if (typed.NumInferenceSteps < 1)
            throw new ValidationException("numInferenceSteps must be >= 1.");
    }

    private static byte[]? DecodeDataUrlToBytes(string dataUrl)
    {
        var idx = dataUrl.IndexOf(",", StringComparison.Ordinal);
        var b64 = idx >= 0 ? dataUrl[(idx + 1)..] : dataUrl;
        if (string.IsNullOrWhiteSpace(b64))
            return null;

        return Convert.FromBase64String(b64);
    }

    private static string BuildImageName(string baseName, int index, string extension)
    {
        var safeBase = baseName.ToOutputFileName();
        return index == 1 ? $"{safeBase}{extension}" : $"{safeBase}-{index}{extension}";
    }
}

[Description("Please confirm the Fireworks FLUX.1 schnell image generation request.")]
public sealed class FireworksFluxSchnellRequest
{
    [JsonPropertyName("prompt")]
    [Required]
    [Description("Prompt describing the image to generate.")]
    public string Prompt { get; set; } = default!;

    [JsonPropertyName("aspect_ratio")]
    [Description("Aspect ratio. Options: 1:1, 21:9, 16:9, 3:2, 5:4, 4:5, 2:3, 9:16, 9:21, 4:3, 3:4.")]
    public string AspectRatio { get; set; } = "16:9";

    [JsonPropertyName("guidance_scale")]
    [Description("Guidance scale.")]
    public double GuidanceScale { get; set; } = 3.5;

    [JsonPropertyName("num_inference_steps")]
    [Description("Number of inference steps.")]
    public int NumInferenceSteps { get; set; } = 4;

    [JsonPropertyName("seed")]
    [Description("Random seed (0 = random).")]
    public int Seed { get; set; } = 0;

    [JsonPropertyName("filename")]
    [Required]
    [Description("Output filename without extension.")]
    public string Filename { get; set; } = default!;

}
