using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Net.Http.Headers;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using MCPhappey.Common.Extensions;
using MCPhappey.Core.Extensions;
using MCPhappey.Core.Services;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.KernelMemory.Pipeline;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;

namespace MCPhappey.Tools.Fireworks;

public static class FireworksTranscriptions
{
    private const string TranscriptionsPath = "/v1/audio/transcriptions";
    private const string TranslationsPath = "/v1/audio/translations";

    [Description("Transcribe audio from fileUrl using Fireworks, returning structured content and uploaded artifacts.")]
    [McpServerTool(
        Title = "Fireworks Audio Transcription",
        Name = "fireworks_audio_transcription",
        Destructive = false,
        OpenWorld = true)]
    public static async Task<CallToolResult?> Fireworks_Audio_Transcription(
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Audio file URL to transcribe (SharePoint/OneDrive/HTTPS supported).")]
        string fileUrl,
        [Description("ASR model: whisper-v3 or whisper-v3-turbo. Default: whisper-v3.")]
        string model = "whisper-v3",
        [Description("VAD model: silero or whisperx-pyannet. Default: silero.")] string vadModel = "silero",
        [Description("Alignment model: mms_fa or tdnn_ffn. Default: mms_fa.")] string alignmentModel = "mms_fa",
        [Description("Optional target language code (e.g., en, nl).")]
        string? language = null,
        [Description("Optional prompt to guide transcription.")]
        string? prompt = null,
        [Description("Sampling temperature (0-1). Default: 0.")]
        double temperature = 0,
        [Description("Response format: json, text, srt, verbose_json, vtt. Default: json.")]
        string responseFormat = "json",
        [Description("Timestamp granularities: word, segment, or word,segment (requires verbose_json).")]
        string? timestampGranularities = null,
        [Description("Enable diarization (true/false). Default: false.")]
        bool diarize = false,
        [Description("Minimum speakers for diarization. Default: 1.")]
        int minSpeakers = 1,
        [Description("Maximum speakers for diarization. Default: 0 (unspecified).")]
        int maxSpeakers = 0,
        [Description("Audio preprocessing mode: none, dynamic, soft_dynamic, bass_dynamic.")]
        string? preprocessing = null,
        [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
            await requestContext.WithStructuredContent(async () =>
            {
                var (typed, notAccepted, _) = await requestContext.Server.TryElicit(
                    new FireworksTranscriptionRequest
                    {
                        FileUrl = fileUrl,
                        Model = model,
                        VadModel = vadModel,
                        AlignmentModel = alignmentModel,
                        Language = language,
                        Prompt = prompt,
                        Temperature = ClampTemperature(temperature),
                        ResponseFormat = NormalizeResponseFormat(responseFormat),
                        TimestampGranularities = timestampGranularities,
                        Diarize = diarize,
                        MinSpeakers = minSpeakers,
                        MaxSpeakers = maxSpeakers,
                        Preprocessing = preprocessing,
                        Filename = filename?.ToOutputFileName() ?? requestContext.ToOutputFileName()
                    },
                    cancellationToken);

                if (notAccepted != null) return notAccepted;
                if (typed == null) return "No input data provided".ToErrorCallToolResponse();

                ValidateTranscriptionRequest(typed);

                return await ExecuteAudioOperationAsync(
                    serviceProvider,
                    requestContext,
                    BuildBaseUrl(typed.Model),
                    TranscriptionsPath,
                    typed,
                    cancellationToken);
            }));

    [Description("Translate audio from fileUrl to English using Fireworks, returning structured content and uploaded artifacts.")]
    [McpServerTool(
        Title = "Fireworks Audio Translation",
        Name = "fireworks_audio_translation",
        Destructive = false,
        OpenWorld = true)]
    public static async Task<CallToolResult?> Fireworks_Audio_Translation(
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Audio file URL to translate (SharePoint/OneDrive/HTTPS supported).")]
        string fileUrl,
        [Description("ASR model: whisper-v3 or whisper-v3-turbo. Default: whisper-v3.")]
        string model = "whisper-v3",
        [Description("VAD model: silero or whisperx-pyannet. Default: silero.")] string vadModel = "silero",
        [Description("Alignment model: mms_fa or tdnn_ffn. Default: mms_fa.")] string alignmentModel = "mms_fa",
        [Description("Optional source language code (e.g., de, fr).")]
        string? language = null,
        [Description("Optional prompt to guide translation.")]
        string? prompt = null,
        [Description("Sampling temperature (0-1). Default: 0.")]
        double temperature = 0,
        [Description("Response format: json, text, srt, verbose_json, vtt. Default: json.")]
        string responseFormat = "json",
        [Description("Timestamp granularities: word, segment, or word,segment (requires verbose_json).")]
        string? timestampGranularities = null,
        [Description("Audio preprocessing mode: none, dynamic, soft_dynamic, bass_dynamic.")]
        string? preprocessing = null,
        [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
            await requestContext.WithStructuredContent(async () =>
            {
                var (typed, notAccepted, _) = await requestContext.Server.TryElicit(
                    new FireworksTranslationRequest
                    {
                        FileUrl = fileUrl,
                        Model = model,
                        VadModel = vadModel,
                        AlignmentModel = alignmentModel,
                        Language = language,
                        Prompt = prompt,
                        Temperature = ClampTemperature(temperature),
                        ResponseFormat = NormalizeResponseFormat(responseFormat),
                        TimestampGranularities = timestampGranularities,
                        Preprocessing = preprocessing,
                        Filename = filename?.ToOutputFileName() ?? requestContext.ToOutputFileName()
                    },
                    cancellationToken);

                if (notAccepted != null) return notAccepted;
                if (typed == null) return "No input data provided".ToErrorCallToolResponse();

                ValidateTranslationRequest(typed);

                return await ExecuteAudioOperationAsync(
                    serviceProvider,
                    requestContext,
                    BuildBaseUrl(typed.Model),
                    TranslationsPath,
                    typed,
                    cancellationToken);
            }));

    private static async Task<CallToolResult?> ExecuteAudioOperationAsync(
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        string baseUrl,
        string path,
        FireworksAudioRequestBase typed,
        CancellationToken cancellationToken)
    {
        var settings = serviceProvider.GetRequiredService<FireworksSettings>();
        var downloadService = serviceProvider.GetRequiredService<DownloadService>();
        var clientFactory = serviceProvider.GetRequiredService<IHttpClientFactory>();

        var downloads = await downloadService.DownloadContentAsync(
            serviceProvider,
            requestContext.Server,
            typed.FileUrl,
            cancellationToken);

        var audioFile = downloads.FirstOrDefault()
            ?? throw new InvalidOperationException("Failed to download audio content from fileUrl.");

        using var form = new MultipartFormDataContent();
        var streamContent = new StreamContent(audioFile.Contents.ToStream());
        streamContent.Headers.ContentType = new MediaTypeHeaderValue(
            string.IsNullOrWhiteSpace(audioFile.MimeType) ? "audio/mpeg" : audioFile.MimeType);
        form.Add(streamContent, "file", string.IsNullOrWhiteSpace(audioFile.Filename) ? "input.audio" : audioFile.Filename);

        form.Add(new StringContent(typed.Model), "model");
        form.Add(new StringContent(typed.VadModel), "vad_model");
        form.Add(new StringContent(typed.AlignmentModel), "alignment_model");
        form.Add(new StringContent(typed.ResponseFormat), "response_format");
        form.Add(new StringContent(typed.Temperature.ToString(CultureInfo.InvariantCulture)), "temperature");

        if (!string.IsNullOrWhiteSpace(typed.Language))
            form.Add(new StringContent(typed.Language), "language");

        if (!string.IsNullOrWhiteSpace(typed.Prompt))
            form.Add(new StringContent(typed.Prompt), "prompt");

        if (!string.IsNullOrWhiteSpace(typed.TimestampGranularities))
            form.Add(new StringContent(typed.TimestampGranularities), "timestamp_granularities");

        if (!string.IsNullOrWhiteSpace(typed.Preprocessing))
            form.Add(new StringContent(typed.Preprocessing), "preprocessing");

        if (typed is FireworksTranscriptionRequest t && t.Diarize)
        {
            form.Add(new StringContent("true"), "diarize");
            if (t.MinSpeakers > 0)
                form.Add(new StringContent(t.MinSpeakers.ToString(CultureInfo.InvariantCulture)), "min_speakers");
            if (t.MaxSpeakers > 0)
                form.Add(new StringContent(t.MaxSpeakers.ToString(CultureInfo.InvariantCulture)), "max_speakers");
        }

        using var client = clientFactory.CreateClient();
        using var req = new HttpRequestMessage(HttpMethod.Post, new Uri(new Uri(baseUrl), path))
        {
            Content = form
        };

        req.Headers.Authorization = new AuthenticationHeaderValue("Bearer", settings.ApiKey);
        req.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(MimeTypes.Json));

        using var response = await client.SendAsync(req, cancellationToken);
        var body = await response.Content.ReadAsStringAsync(cancellationToken);

        if (!response.IsSuccessStatusCode)
            throw new InvalidOperationException($"Fireworks audio call failed ({(int)response.StatusCode}): {body}");

        var structured = TryParseStructured(body, typed.ResponseFormat);
        var text = ExtractText(body, typed.ResponseFormat);

        var safeBase = typed.Filename.ToOutputFileName();
        var textExt = GetTextExtension(typed.ResponseFormat);
        var uploadName = string.IsNullOrWhiteSpace(textExt) ? $"{safeBase}.txt" : $"{safeBase}.{textExt}";
        var uploadedTxt = await requestContext.Server.Upload(
            serviceProvider,
            uploadName,
            BinaryData.FromString(text ?? string.Empty),
            cancellationToken);

        var uploadedJson = await requestContext.Server.Upload(
            serviceProvider,
            $"{safeBase}.json",
            BinaryData.FromString(body),
            cancellationToken);

        return new CallToolResult
        {
            StructuredContent = structured,
            Content = new List<ContentBlock>
            {
                (text ?? string.Empty).ToTextContentBlock(),
                uploadedTxt!,
                uploadedJson!
            }
        };
    }

    private static string BuildBaseUrl(string model)
        => string.Equals(model, "whisper-v3-turbo", StringComparison.OrdinalIgnoreCase)
            ? "https://audio-turbo.api.fireworks.ai"
            : "https://audio-prod.api.fireworks.ai";

    private static string NormalizeResponseFormat(string? responseFormat)
    {
        var value = string.IsNullOrWhiteSpace(responseFormat)
            ? "json"
            : responseFormat.Trim().ToLowerInvariant();

        return value switch
        {
            "json" or "text" or "srt" or "verbose_json" or "vtt" => value,
            _ => "json"
        };
    }

    private static double ClampTemperature(double temperature)
        => Math.Clamp(temperature, 0, 1);

    private static void ValidateTranscriptionRequest(FireworksTranscriptionRequest typed)
    {
        ValidateCommonAudioRequest(typed);

        if (typed.Diarize)
        {
            if (!string.Equals(typed.ResponseFormat, "verbose_json", StringComparison.OrdinalIgnoreCase))
                throw new ValidationException("responseFormat must be verbose_json when diarize is true.");

            if (string.IsNullOrWhiteSpace(typed.TimestampGranularities)
                || !typed.TimestampGranularities.Contains("word", StringComparison.OrdinalIgnoreCase))
                throw new ValidationException("timestampGranularities must include 'word' when diarize is true.");
        }
    }

    private static void ValidateTranslationRequest(FireworksTranslationRequest typed)
        => ValidateCommonAudioRequest(typed);

    private static void ValidateCommonAudioRequest(FireworksAudioRequestBase typed)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(typed.FileUrl);
        ArgumentException.ThrowIfNullOrWhiteSpace(typed.Model);

        if (!string.Equals(typed.Model, "whisper-v3", StringComparison.OrdinalIgnoreCase)
            && !string.Equals(typed.Model, "whisper-v3-turbo", StringComparison.OrdinalIgnoreCase))
            throw new ValidationException("model must be whisper-v3 or whisper-v3-turbo.");

        if (!string.IsNullOrWhiteSpace(typed.VadModel)
            && !string.Equals(typed.VadModel, "silero", StringComparison.OrdinalIgnoreCase)
            && !string.Equals(typed.VadModel, "whisperx-pyannet", StringComparison.OrdinalIgnoreCase))
            throw new ValidationException("vadModel must be silero or whisperx-pyannet.");

        if (!string.IsNullOrWhiteSpace(typed.AlignmentModel)
            && !string.Equals(typed.AlignmentModel, "mms_fa", StringComparison.OrdinalIgnoreCase)
            && !string.Equals(typed.AlignmentModel, "tdnn_ffn", StringComparison.OrdinalIgnoreCase))
            throw new ValidationException("alignmentModel must be mms_fa or tdnn_ffn.");

        if (!string.IsNullOrWhiteSpace(typed.Preprocessing))
        {
            var allowed = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                "none", "dynamic", "soft_dynamic", "bass_dynamic"
            };
            if (!allowed.Contains(typed.Preprocessing))
                throw new ValidationException("preprocessing must be one of: none, dynamic, soft_dynamic, bass_dynamic.");
        }
    }

    private static JsonNode TryParseStructured(string body, string responseFormat)
    {
        if (!string.Equals(responseFormat, "json", StringComparison.OrdinalIgnoreCase)
            && !string.Equals(responseFormat, "verbose_json", StringComparison.OrdinalIgnoreCase))
        {
            return new JsonObject
            {
                ["text"] = body
            };
        }

        try
        {
            return JsonNode.Parse(body) ?? new JsonObject();
        }
        catch
        {
            return new JsonObject
            {
                ["raw"] = body
            };
        }
    }

    private static string ExtractText(string responseBody, string responseFormat)
    {
        if (!string.Equals(responseFormat, "json", StringComparison.OrdinalIgnoreCase)
            && !string.Equals(responseFormat, "verbose_json", StringComparison.OrdinalIgnoreCase))
            return responseBody;

        try
        {
            using var doc = JsonDocument.Parse(responseBody);
            if (doc.RootElement.TryGetProperty("text", out var text) && text.ValueKind == JsonValueKind.String)
                return text.GetString() ?? string.Empty;
        }
        catch
        {
            return responseBody;
        }

        return responseBody;
    }

    private static string GetTextExtension(string responseFormat)
        => responseFormat switch
        {
            "srt" => "srt",
            "vtt" => "vtt",
            _ => "txt"
        };
}

public abstract class FireworksAudioRequestBase
{
    [JsonPropertyName("fileUrl")]
    [Required]
    [Description("Audio file URL to process.")]
    public string FileUrl { get; set; } = default!;

    [JsonPropertyName("model")]
    [Required]
    [Description("Model name: whisper-v3 or whisper-v3-turbo.")]
    public string Model { get; set; } = "whisper-v3";

    [JsonPropertyName("vad_model")]
    [Description("VAD model: silero or whisperx-pyannet.")]
    public string VadModel { get; set; } = "silero";

    [JsonPropertyName("alignment_model")]
    [Description("Alignment model: mms_fa or tdnn_ffn.")]
    public string AlignmentModel { get; set; } = "mms_fa";

    [JsonPropertyName("language")]
    [Description("Optional language code.")]
    public string? Language { get; set; }

    [JsonPropertyName("prompt")]
    [Description("Optional prompt to guide decoding.")]
    public string? Prompt { get; set; }

    [JsonPropertyName("temperature")]
    [Range(0, 1)]
    [Description("Sampling temperature between 0 and 1.")]
    public double Temperature { get; set; } = 0;

    [JsonPropertyName("response_format")]
    [Required]
    [Description("json, text, srt, verbose_json, or vtt.")]
    public string ResponseFormat { get; set; } = "json";

    [JsonPropertyName("timestamp_granularities")]
    [Description("Timestamp granularities: word, segment, or word,segment (requires verbose_json).")]
    public string? TimestampGranularities { get; set; }

    [JsonPropertyName("preprocessing")]
    [Description("Preprocessing mode: none, dynamic, soft_dynamic, bass_dynamic.")]
    public string? Preprocessing { get; set; }

    [JsonPropertyName("filename")]
    [Required]
    [Description("Output filename without extension.")]
    public string Filename { get; set; } = default!;
}

[Description("Please confirm the Fireworks transcription request.")]
public sealed class FireworksTranscriptionRequest : FireworksAudioRequestBase
{
    [JsonPropertyName("diarize")]
    [Description("Enable diarization.")]
    public bool Diarize { get; set; } = false;

    [JsonPropertyName("min_speakers")]
    [Description("Minimum number of speakers.")]
    public int MinSpeakers { get; set; } = 1;

    [JsonPropertyName("max_speakers")]
    [Description("Maximum number of speakers.")]
    public int MaxSpeakers { get; set; } = 0;

}

[Description("Please confirm the Fireworks translation request.")]
public sealed class FireworksTranslationRequest : FireworksAudioRequestBase
{
   
}
