using System.ComponentModel;
using MCPhappey.Core.Extensions;
using Microsoft.Extensions.DependencyInjection;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MCPhappey.Common.Extensions;

namespace MCPhappey.Tools.EdenAI.Audio;

public static class EdenAIAudio
{
    [Description("Convert text into speech using Eden AI text-to-speech providers.")]
    [McpServerTool(
        Title = "EdenAI Text-to-Speech",
        Name = "edenai_audio_text_to_speech",
        Destructive = false)]
    public static async Task<CallToolResult?> EdenAI_AudioTextToSpeech(
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("The text to convert into speech.")] string text,
        [Description("Primary provider, e.g. openai, google, microsoft, elevenlabs.")] string provider = "openai",
        [Description("Optional fallback providers (comma separated).")] string? fallbackProviders = null,
        [Description("Language code (e.g. en, fr, de, nl).")] string? language = "en",
        [Description("Audio format (mp3, wav, ogg). Default: mp3.")] string audioFormat = "mp3",
        [Description("Speech rate (-100 to 100). Default: 0.")] int rate = 0,
        [Description("Speech pitch (-100 to 100). Default: 0.")] int pitch = 0,
        [Description("Volume adjustment (-100 to 100). Default: 0.")] int volume = 0,
        [Description("Sampling rate (Hz, optional). Default: 0.")] int samplingRate = 0,
        [Description("Output filename (without extension). Default autogenerated.")] string? filename = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
        {
            // 1️⃣ Elicit missing parameters
            var (typed, notAccepted, _) = await requestContext.Server.TryElicit(
                new EdenAIAudioTextToSpeechRequest
                {
                    Text = text,
                    Provider = provider,
                    FallbackProviders = fallbackProviders,
                    Language = language,
                    AudioFormat = audioFormat,
                    Rate = rate,
                    Pitch = pitch,
                    Volume = volume,
                    SamplingRate = samplingRate,
                    Filename = filename?.ToOutputFileName() ?? requestContext.ToOutputFileName()
                },
                cancellationToken);

            // 2️⃣ Prepare EdenAI client
            var eden = serviceProvider.GetRequiredService<EdenAIClient>();

            // 3️⃣ Build JSON payload
            var payload = new Dictionary<string, object?>
            {
                ["providers"] = typed.Provider,
                ["text"] = typed.Text,
                ["language"] = typed.Language,
                ["audio_format"] = typed.AudioFormat,
                ["rate"] = typed.Rate,
                ["pitch"] = typed.Pitch,
                ["volume"] = typed.Volume,
                ["sampling_rate"] = typed.SamplingRate,
                ["response_as_dict"] = true,
                ["show_original_response"] = false,
                ["show_base_64"] = true
            };

            if (!string.IsNullOrWhiteSpace(typed.FallbackProviders))
                payload["fallback_providers"] = typed.FallbackProviders;

            // 4️⃣ Make Eden AI request
            var resultNode = await eden.PostAsync("audio/text_to_speech/", payload, cancellationToken)
                ?? throw new Exception("Eden AI returned no response.");

            // 5️⃣ Extract audio content (provider-specific)
            var providerKey = resultNode.AsObject().First().Key;
            var providerResult = resultNode[providerKey];
            var audioBase64 = providerResult?["audio"]?.GetValue<string>();
            var audioUrl = providerResult?["audio_resource_url"]?.GetValue<string>();
            var status = providerResult?["status"]?.GetValue<string>();

            if (status != "success" || string.IsNullOrWhiteSpace(audioBase64))
                throw new Exception("Eden AI TTS generation failed or returned empty audio.");

            // 6️⃣ Convert base64 → BinaryData
            var binary = Convert.FromBase64String(audioBase64);
            var binaryData = BinaryData.FromBytes(binary);

            // 7️⃣ Upload to Graph
            var fileExt = typed.AudioFormat switch
            {
                "wav" => "wav",
                "ogg" => "ogg",
                _ => "mp3"
            };

            var uploaded = await requestContext.Server.Upload(
                serviceProvider,
                $"{typed.Filename}.{fileExt}",
                binaryData,
                cancellationToken);

            // 8️⃣ Return structured result
            return new CallToolResult
            {
                StructuredContent = resultNode,
                Content =
                [
                    uploaded!,
                    new AudioContentBlock
                    {
                        Data = Convert.ToBase64String(binary),
                        MimeType = fileExt == "wav" ? "audio/wav" :
                                   fileExt == "ogg" ? "audio/ogg" : "audio/mpeg"
                    }
                ]
            };
        });

    [Description("Please fill in the Eden AI text-to-speech request details.")]
    public class EdenAIAudioTextToSpeechRequest
    {
        [Required]
        [JsonPropertyName("text")]
        [Description("Text to convert to speech.")]
        public string Text { get; set; } = default!;

        [Required]
        [JsonPropertyName("provider")]
        [Description("Primary Eden AI provider (e.g. openai, google, microsoft, elevenlabs).")]
        public string Provider { get; set; } = "openai";

        [JsonPropertyName("fallback_providers")]
        [Description("Optional fallback providers (comma separated).")]
        public string? FallbackProviders { get; set; }

        [JsonPropertyName("language")]
        [Description("Language code (e.g. en, fr, de, nl).")]
        public string? Language { get; set; } = "en";

        [JsonPropertyName("audio_format")]
        [Description("Audio format (mp3, wav, ogg).")]
        public string AudioFormat { get; set; } = "mp3";

        [JsonPropertyName("rate")]
        [Range(-100, 100)]
        [Description("Speech rate adjustment (-100 to 100).")]
        public int Rate { get; set; } = 0;

        [JsonPropertyName("pitch")]
        [Range(-100, 100)]
        [Description("Speech pitch adjustment (-100 to 100).")]
        public int Pitch { get; set; } = 0;

        [JsonPropertyName("volume")]
        [Range(-100, 100)]
        [Description("Volume adjustment (-100 to 100).")]
        public int Volume { get; set; } = 0;

        [JsonPropertyName("sampling_rate")]
        [Range(0, 200000)]
        [Description("Sampling rate (Hz, optional). Default: 0.")]
        public int SamplingRate { get; set; } = 0;

        [JsonPropertyName("filename")]
        [Description("Output filename without extension.")]
        public string Filename { get; set; } = default!;
    }
}