// <auto-generated />
using System;
using MCPhappey.Servers.SQL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MCPhappey.Servers.SQL.Migrations
{
    [DbContext(typeof(McpDatabaseContext))]
    [Migration("20250922082647_ServerDescription")]
    partial class ServerDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.Icon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sizes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Icons");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.Prompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromptTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("Prompts");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.PromptArgument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PromptId")
                        .HasColumnType("int");

                    b.Property<bool?>("Required")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PromptId");

                    b.ToTable("PromptArguments");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.PromptIcon", b =>
                {
                    b.Property<int>("PromptId")
                        .HasColumnType("int");

                    b.Property<int>("IconId")
                        .HasColumnType("int");

                    b.HasKey("PromptId", "IconId");

                    b.HasIndex("IconId");

                    b.ToTable("PromptIcons");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AssistantAudience")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Priority")
                        .HasColumnType("real");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("UserAudience")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.ResourceIcon", b =>
                {
                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("IconId")
                        .HasColumnType("int");

                    b.HasKey("ResourceId", "IconId");

                    b.HasIndex("IconId");

                    b.ToTable("ResourceIcons");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.ResourceTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AssistantAudience")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Priority")
                        .HasColumnType("real");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("UserAudience")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("ResourceTemplates");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Hidden")
                        .HasColumnType("bit");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Secured")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.ServerApiKey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<int>("ServerId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id", "ServerId");

                    b.HasIndex("ServerId");

                    b.ToTable("ServerApiKeys");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.ServerGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<int>("ServerId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("Id", "ServerId");

                    b.HasIndex("ServerId");

                    b.ToTable("ServerGroups");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.ServerIcon", b =>
                {
                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<int>("IconId")
                        .HasColumnType("int");

                    b.HasKey("ServerId", "IconId");

                    b.HasIndex("IconId");

                    b.ToTable("ServerIcons");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.ServerOwner", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<int>("ServerId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("Id", "ServerId");

                    b.HasIndex("ServerId");

                    b.ToTable("ServerOwners");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.ServerTool", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<int>("ServerId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("Name", "ServerId");

                    b.HasIndex("ServerId");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.Prompt", b =>
                {
                    b.HasOne("MCPhappey.Servers.SQL.Models.Server", "Server")
                        .WithMany("Prompts")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.PromptArgument", b =>
                {
                    b.HasOne("MCPhappey.Servers.SQL.Models.Prompt", "Prompt")
                        .WithMany("Arguments")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.PromptIcon", b =>
                {
                    b.HasOne("MCPhappey.Servers.SQL.Models.Icon", "Icon")
                        .WithMany("PromptIcons")
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MCPhappey.Servers.SQL.Models.Prompt", "Prompt")
                        .WithMany("Icons")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Icon");

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.Resource", b =>
                {
                    b.HasOne("MCPhappey.Servers.SQL.Models.Server", "Server")
                        .WithMany("Resources")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.ResourceIcon", b =>
                {
                    b.HasOne("MCPhappey.Servers.SQL.Models.Icon", "Icon")
                        .WithMany("ResourceIcons")
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MCPhappey.Servers.SQL.Models.Resource", "Resource")
                        .WithMany("Icons")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Icon");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.ResourceTemplate", b =>
                {
                    b.HasOne("MCPhappey.Servers.SQL.Models.Server", "Server")
                        .WithMany("ResourceTemplates")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.ServerApiKey", b =>
                {
                    b.HasOne("MCPhappey.Servers.SQL.Models.Server", "Server")
                        .WithMany("ApiKeys")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.ServerGroup", b =>
                {
                    b.HasOne("MCPhappey.Servers.SQL.Models.Server", "Server")
                        .WithMany("Groups")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.ServerIcon", b =>
                {
                    b.HasOne("MCPhappey.Servers.SQL.Models.Icon", "Icon")
                        .WithMany("ServerIcons")
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MCPhappey.Servers.SQL.Models.Server", "Server")
                        .WithMany("Icons")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Icon");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.ServerOwner", b =>
                {
                    b.HasOne("MCPhappey.Servers.SQL.Models.Server", "Server")
                        .WithMany("Owners")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.ServerTool", b =>
                {
                    b.HasOne("MCPhappey.Servers.SQL.Models.Server", "Server")
                        .WithMany("Tools")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.Icon", b =>
                {
                    b.Navigation("PromptIcons");

                    b.Navigation("ResourceIcons");

                    b.Navigation("ServerIcons");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.Prompt", b =>
                {
                    b.Navigation("Arguments");

                    b.Navigation("Icons");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.Resource", b =>
                {
                    b.Navigation("Icons");
                });

            modelBuilder.Entity("MCPhappey.Servers.SQL.Models.Server", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Groups");

                    b.Navigation("Icons");

                    b.Navigation("Owners");

                    b.Navigation("Prompts");

                    b.Navigation("ResourceTemplates");

                    b.Navigation("Resources");

                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
