// <auto-generated />
using System;
using MCPhappey.Servers.SQL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MCPhappey.Servers.SQL.Migrations
{
    [DbContext(typeof(McpDatabaseContext))]
    [Migration("20250516152903_ServerGroups")]
    partial class ServerGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.Prompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromptTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("Prompts");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.PromptArgument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PromptId")
                        .HasColumnType("int");

                    b.Property<bool?>("Required")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PromptId");

                    b.ToTable("PromptArguments");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.PromptResource", b =>
                {
                    b.Property<int>("PromptId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.HasKey("PromptId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("PromptResources");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.PromptResourceTemplate", b =>
                {
                    b.Property<int>("PromptId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceTemplateId")
                        .HasColumnType("int");

                    b.HasKey("PromptId", "ResourceTemplateId");

                    b.HasIndex("ResourceTemplateId");

                    b.ToTable("PromptResourceTemplates");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.ResourceTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("ResourceTemplates");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Secured")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.ServerApiKey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<int>("ServerId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id", "ServerId");

                    b.HasIndex("ServerId");

                    b.ToTable("ServerApiKeys");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.ServerGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<int>("ServerId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("Id", "ServerId");

                    b.HasIndex("ServerId");

                    b.ToTable("ServerGroups");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.ServerOwner", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<int>("ServerId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("Id", "ServerId");

                    b.HasIndex("ServerId");

                    b.ToTable("ServerOwners");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.ServerTool", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<int>("ServerId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("Name", "ServerId");

                    b.HasIndex("ServerId");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.Prompt", b =>
                {
                    b.HasOne("AIssistant.Tools.Core.Models.Database.Server", "Server")
                        .WithMany("Prompts")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.PromptArgument", b =>
                {
                    b.HasOne("AIssistant.Tools.Core.Models.Database.Prompt", "Prompt")
                        .WithMany("Arguments")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.PromptResource", b =>
                {
                    b.HasOne("AIssistant.Tools.Core.Models.Database.Prompt", "Prompt")
                        .WithMany("PromptResources")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIssistant.Tools.Core.Models.Database.Resource", "Resource")
                        .WithMany("PromptResources")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prompt");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.PromptResourceTemplate", b =>
                {
                    b.HasOne("AIssistant.Tools.Core.Models.Database.Prompt", "Prompt")
                        .WithMany("PromptResourceTemplates")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIssistant.Tools.Core.Models.Database.ResourceTemplate", "ResourceTemplate")
                        .WithMany("PromptResourceTemplates")
                        .HasForeignKey("ResourceTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prompt");

                    b.Navigation("ResourceTemplate");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.Resource", b =>
                {
                    b.HasOne("AIssistant.Tools.Core.Models.Database.Server", "Server")
                        .WithMany("Resources")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.ResourceTemplate", b =>
                {
                    b.HasOne("AIssistant.Tools.Core.Models.Database.Server", "Server")
                        .WithMany("ResourceTemplates")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.ServerApiKey", b =>
                {
                    b.HasOne("AIssistant.Tools.Core.Models.Database.Server", "Server")
                        .WithMany("ApiKeys")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.ServerGroup", b =>
                {
                    b.HasOne("AIssistant.Tools.Core.Models.Database.Server", "Server")
                        .WithMany("Groups")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.ServerOwner", b =>
                {
                    b.HasOne("AIssistant.Tools.Core.Models.Database.Server", "Server")
                        .WithMany("Owners")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.ServerTool", b =>
                {
                    b.HasOne("AIssistant.Tools.Core.Models.Database.Server", "Server")
                        .WithMany("Tools")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.Prompt", b =>
                {
                    b.Navigation("Arguments");

                    b.Navigation("PromptResourceTemplates");

                    b.Navigation("PromptResources");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.Resource", b =>
                {
                    b.Navigation("PromptResources");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.ResourceTemplate", b =>
                {
                    b.Navigation("PromptResourceTemplates");
                });

            modelBuilder.Entity("AIssistant.Tools.Core.Models.Database.Server", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Groups");

                    b.Navigation("Owners");

                    b.Navigation("Prompts");

                    b.Navigation("ResourceTemplates");

                    b.Navigation("Resources");

                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
