using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;
using MCPhappey.Common.Extensions;
using MCPhappey.Common.Models;
using MCPhappey.Core.Extensions;
using MCPhappey.Core.Services;
using Microsoft.Extensions.DependencyInjection;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;

namespace MCPhappey.Tools.AIML.Images;

public static partial class AIMLImages
{
    [Description("Generate an image using Google Imagen 4 model for balanced speed and quality.")]
    [McpServerTool(
          Title = "Generate image with Google Imagen 4",
          Name = "aiml_images_imagen4_generate",
          Destructive = false)]
    public static async Task<CallToolResult?> AIMLImages_Imagen4Generate(
          [Description("Prompt for the image generation (max 400 chars)."), MaxLength(400)] string prompt,
          IServiceProvider serviceProvider,
          RequestContext<CallToolRequestParams> requestContext,
          [Description("Number of images to generate (1–4)."), Range(1, 4)] int numImages = 1,
          [Description("Aspect ratio of the image. Default: 1:1 (options: 1:1, 9:16, 16:9, 3:4, 4:3).")] string aspectRatio = "1:1",
          [Description("Enhance prompt with LLM rewriting for higher-quality images. Default: true.")] bool enhancePrompt = true,
          [Description("Allow generation of people (allow_adult or dont_allow). Default: allow_adult.")] string personGeneration = "allow_adult",
          [Description("Safety setting (block_low_and_above, block_medium_and_above, block_only_high). Default: block_medium_and_above.")] string safetySetting = "block_medium_and_above",
          [Description("Add invisible watermark. Default: false.")] bool addWatermark = false,
          [Description("Seed for deterministic results (0 for random).")] uint? seed = null,
          [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
          CancellationToken cancellationToken = default)
          => await requestContext.WithExceptionCheck(async () =>
          {
              var settings = serviceProvider.GetRequiredService<AIMLSettings>();
              var downloadService = serviceProvider.GetRequiredService<DownloadService>();

              // Step 1: Ask user for confirmation / edits
              var (typed, notAccepted, _) = await requestContext.Server.TryElicit(
                  new AIMLNewImagenStandard
                  {
                      Prompt = prompt,
                      NumImages = numImages,
                      AspectRatio = aspectRatio,
                      EnhancePrompt = enhancePrompt,
                      PersonGeneration = personGeneration,
                      SafetySetting = safetySetting,
                      AddWatermark = addWatermark,
                      Seed = seed,
                      Filename = filename?.ToOutputFileName() ?? requestContext.ToOutputFileName("png"),
                  },
                  cancellationToken);

              // Step 2: Build payload
              var body = new
              {
                  model = "google/imagen-4.0-generate-001",
                  prompt = typed.Prompt,
                  num_images = typed.NumImages,
                  aspect_ratio = typed.AspectRatio,
                  enhance_prompt = typed.EnhancePrompt,
                  person_generation = typed.PersonGeneration,
                  safety_setting = typed.SafetySetting,
                  add_watermark = typed.AddWatermark,
                  convert_base64_to_url = true,
                  seed = typed.Seed == 0 ? null : typed.Seed
              };

              // Step 3: POST to AIML API
              var aiml = serviceProvider.GetRequiredService<AIMLClient>();
              var doc = await aiml.PostAsync(BASE_URL, body, cancellationToken);
              var dataArray = doc.RootElement.GetProperty("data");

              if (dataArray.GetArrayLength() == 0)
                  throw new Exception("No image data returned from AI/ML API.");

              var allUploads = new List<ContentBlock>();

              foreach (var item in dataArray.EnumerateArray())
              {
                  var url = item.GetProperty("url").GetString();
                  if (string.IsNullOrWhiteSpace(url))
                      continue;

                  var filesData = await downloadService.DownloadContentAsync(
                      serviceProvider, requestContext.Server, url, cancellationToken);

                  foreach (var file in filesData)
                  {
                      var safeName = $"{Path.GetFileNameWithoutExtension(typed.Filename)}_{Guid.NewGuid():N}.png";
                      var uploaded = await requestContext.Server.Upload(
                          serviceProvider, safeName, file.Contents, cancellationToken);

                      if (uploaded != null)
                          allUploads.Add(uploaded);
                  }
              }

              if (allUploads.Count == 0)
                  throw new Exception("No images could be downloaded or uploaded.");

              return new CallToolResult()
              {
                  Content =
                  [
                      .. allUploads,
                    doc.ToJsonContent(BASE_URL)
                  ]
              };
          });

    [Description("Please fill in the Google Imagen 4 image request details.")]
    public class AIMLNewImagenStandard
    {
        [JsonPropertyName("prompt")]
        [Required]
        [Description("The text prompt describing the image.")]
        public string Prompt { get; set; } = default!;

        [JsonPropertyName("num_images")]
        [Range(1, 4)]
        [Description("Number of images to generate.")]
        public int NumImages { get; set; } = 1;

        [JsonPropertyName("aspect_ratio")]
        [Description("The aspect ratio of the image (1:1, 9:16, 16:9, 3:4, 4:3).")]
        public string AspectRatio { get; set; } = "1:1";

        [JsonPropertyName("enhance_prompt")]
        [Description("Use LLM-enhanced prompt rewriting.")]
        public bool EnhancePrompt { get; set; } = true;

        [JsonPropertyName("person_generation")]
        [Description("Allow people generation (allow_adult, dont_allow).")]
        public string PersonGeneration { get; set; } = "allow_adult";

        [JsonPropertyName("safety_setting")]
        [Description("Safety filter level (block_low_and_above, block_medium_and_above, block_only_high).")]
        public string SafetySetting { get; set; } = "block_medium_and_above";

        [JsonPropertyName("add_watermark")]
        [Description("Add invisible watermark.")]
        public bool AddWatermark { get; set; } = false;

        [JsonPropertyName("seed")]
        [Description("Random seed (use 0 for random).")]
        public uint? Seed { get; set; }

        [JsonPropertyName("filename")]
        [Required]
        [Description("The output image file name.")]
        public string Filename { get; set; } = default!;
    }

    [Description("Generate an image using Google Imagen 4 Fast model for quick, high-quality results.")]
    [McpServerTool(
           Title = "Generate image with Google Imagen 4 Fast",
           Name = "aiml_images_imagen4_fast_generate",
           Destructive = false)]
    public static async Task<CallToolResult?> AIMLImages_Imagen4FastGenerate(
           [Description("Prompt for the image generation (max 400 chars)."), MaxLength(400)] string prompt,
           IServiceProvider serviceProvider,
           RequestContext<CallToolRequestParams> requestContext,
           [Description("Number of images to generate (1–4)."), Range(1, 4)] int numImages = 1,
           [Description("Aspect ratio of the image. Default: 1:1 (options: 1:1, 9:16, 16:9, 3:4, 4:3).")] string aspectRatio = "1:1",
           [Description("Enhance prompt with LLM rewriting for higher-quality images. Default: true.")] bool enhancePrompt = true,
           [Description("Allow generation of people (allow_adult or dont_allow). Default: allow_adult.")] string personGeneration = "allow_adult",
           [Description("Safety setting (block_low_and_above, block_medium_and_above, block_only_high). Default: block_medium_and_above.")] string safetySetting = "block_medium_and_above",
           [Description("Add invisible watermark. Default: false.")] bool addWatermark = false,
           [Description("Seed for deterministic results (0 for random).")] uint? seed = null,
           [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
           CancellationToken cancellationToken = default)
           => await requestContext.WithExceptionCheck(async () =>
           {
               var settings = serviceProvider.GetRequiredService<AIMLSettings>();
               var downloadService = serviceProvider.GetRequiredService<DownloadService>();

               // Step 1: Ask user for confirmation / edits
               var (typed, notAccepted, _) = await requestContext.Server.TryElicit(
                   new AIMLNewImagenFast
                   {
                       Prompt = prompt,
                       NumImages = numImages,
                       AspectRatio = aspectRatio,
                       EnhancePrompt = enhancePrompt,
                       PersonGeneration = personGeneration,
                       SafetySetting = safetySetting,
                       AddWatermark = addWatermark,
                       Seed = seed,
                       Filename = filename?.ToOutputFileName() ?? requestContext.ToOutputFileName("png"),
                   },
                   cancellationToken);

               // Step 2: Build payload
               var body = new
               {
                   model = "google/imagen-4.0-fast-generate-001",
                   prompt = typed.Prompt,
                   num_images = typed.NumImages,
                   aspect_ratio = typed.AspectRatio,
                   enhance_prompt = typed.EnhancePrompt,
                   person_generation = typed.PersonGeneration,
                   safety_setting = typed.SafetySetting,
                   add_watermark = typed.AddWatermark,
                   convert_base64_to_url = true,
                   seed = typed.Seed == 0 ? null : typed.Seed
               };

               // Step 3: POST to AIML API
               var aiml = serviceProvider.GetRequiredService<AIMLClient>();
               var doc = await aiml.PostAsync(BASE_URL, body, cancellationToken);
               var dataArray = doc.RootElement.GetProperty("data");

               if (dataArray.GetArrayLength() == 0)
                   throw new Exception("No image data returned from AI/ML API.");

               var allUploads = new List<ContentBlock>();

               foreach (var item in dataArray.EnumerateArray())
               {
                   var url = item.GetProperty("url").GetString();
                   if (string.IsNullOrWhiteSpace(url))
                       continue;

                   var filesData = await downloadService.DownloadContentAsync(
                       serviceProvider, requestContext.Server, url, cancellationToken);

                   foreach (var file in filesData)
                   {
                       var safeName = $"{Path.GetFileNameWithoutExtension(typed.Filename)}_{Guid.NewGuid():N}.png";
                       var uploaded = await requestContext.Server.Upload(
                           serviceProvider, safeName, file.Contents, cancellationToken);

                       if (uploaded != null)
                           allUploads.Add(uploaded);
                   }
               }

               if (allUploads.Count == 0)
                   throw new Exception("No images could be downloaded or uploaded.");

               return new CallToolResult()
               {
                   Content =
                   [
                       .. allUploads,
                    doc.ToJsonContent(BASE_URL)
                   ]
               };
           });

    [Description("Please fill in the Google Imagen Fast image request details.")]
    public class AIMLNewImagenFast
    {
        [JsonPropertyName("prompt")]
        [Required]
        [Description("The text prompt describing the image.")]
        public string Prompt { get; set; } = default!;

        [JsonPropertyName("num_images")]
        [Range(1, 4)]
        [Description("Number of images to generate.")]
        public int NumImages { get; set; } = 1;

        [JsonPropertyName("aspect_ratio")]
        [Description("The aspect ratio of the image (1:1, 9:16, 16:9, 3:4, 4:3).")]
        public string AspectRatio { get; set; } = "1:1";

        [JsonPropertyName("enhance_prompt")]
        [Description("Use LLM-enhanced prompt rewriting.")]
        public bool EnhancePrompt { get; set; } = true;

        [JsonPropertyName("person_generation")]
        [Description("Allow people generation (allow_adult, dont_allow).")]
        public string PersonGeneration { get; set; } = "allow_adult";

        [JsonPropertyName("safety_setting")]
        [Description("Safety filter level (block_low_and_above, block_medium_and_above, block_only_high).")]
        public string SafetySetting { get; set; } = "block_medium_and_above";

        [JsonPropertyName("add_watermark")]
        [Description("Add invisible watermark.")]
        public bool AddWatermark { get; set; } = false;

        [JsonPropertyName("seed")]
        [Description("Random seed (use 0 for random).")]
        public uint? Seed { get; set; }

        [JsonPropertyName("filename")]
        [Required]
        [Description("The output image file name.")]
        public string Filename { get; set; } = default!;
    }

    [Description("Generate a photorealistic image using Google Imagen 4 Ultra model.")]
    [McpServerTool(
        Title = "Generate image with Google Imagen 4 Ultra",
        Name = "aiml_images_imagen4_ultra_generate",
        Destructive = false)]
    public static async Task<CallToolResult?> AIMLImages_Imagen4UltraGenerate(
        [Description("Prompt for the image generation (max 400 chars)."), MaxLength(400)] string prompt,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Number of images to generate (1–4)."), Range(1, 4)] int numImages = 1,
        [Description("Aspect ratio of the image. Default: 1:1 (options: 1:1, 9:16, 16:9, 3:4, 4:3).")] string aspectRatio = "1:1",
        [Description("Enhance prompt with LLM rewriting for higher-quality images. Default: true.")] bool enhancePrompt = true,
        [Description("Allow generation of people (allow_adult or dont_allow). Default: allow_adult.")] string personGeneration = "allow_adult",
        [Description("Safety setting (block_low_and_above, block_medium_and_above, block_only_high). Default: block_medium_and_above.")] string safetySetting = "block_medium_and_above",
        [Description("Add invisible watermark. Default: false.")] bool addWatermark = false,
        [Description("Seed for deterministic results (0 for random).")] uint? seed = null,
        [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
        CancellationToken cancellationToken = default)
        => await requestContext.WithExceptionCheck(async () =>
        {
            var settings = serviceProvider.GetRequiredService<AIMLSettings>();
            var downloadService = serviceProvider.GetRequiredService<DownloadService>();

            // Step 1: Ask user for confirmation / edits
            var (typed, notAccepted, _) = await requestContext.Server.TryElicit(
                new AIMLNewImagenUltra
                {
                    Prompt = prompt,
                    NumImages = numImages,
                    AspectRatio = aspectRatio,
                    EnhancePrompt = enhancePrompt,
                    PersonGeneration = personGeneration,
                    SafetySetting = safetySetting,
                    AddWatermark = addWatermark,
                    Seed = seed,
                    Filename = filename?.ToOutputFileName() ?? requestContext.ToOutputFileName("png"),
                },
                cancellationToken);

            // Step 2: Build payload
            var body = new
            {
                model = "google/imagen-4.0-ultra-generate-001",
                prompt = typed.Prompt,
                num_images = typed.NumImages,
                aspect_ratio = typed.AspectRatio,
                enhance_prompt = typed.EnhancePrompt,
                person_generation = typed.PersonGeneration,
                safety_setting = typed.SafetySetting,
                add_watermark = typed.AddWatermark,
                convert_base64_to_url = true,
                seed = typed.Seed == 0 ? null : typed.Seed
            };

            // Step 3: POST to AIML API
            var aiml = serviceProvider.GetRequiredService<AIMLClient>();
            var doc = await aiml.PostAsync(BASE_URL, body, cancellationToken);
            var dataArray = doc.RootElement.GetProperty("data");

            if (dataArray.GetArrayLength() == 0)
                throw new Exception("No image data returned from AI/ML API.");

            var allUploads = new List<ContentBlock>();

            foreach (var item in dataArray.EnumerateArray())
            {
                var url = item.GetProperty("url").GetString();
                if (string.IsNullOrWhiteSpace(url))
                    continue;

                var filesData = await downloadService.DownloadContentAsync(
                    serviceProvider, requestContext.Server, url, cancellationToken);

                foreach (var file in filesData)
                {
                    var safeName = $"{Path.GetFileNameWithoutExtension(typed.Filename)}_{Guid.NewGuid():N}.png";
                    var uploaded = await requestContext.Server.Upload(
                        serviceProvider, safeName, file.Contents, cancellationToken);

                    if (uploaded != null)
                        allUploads.Add(uploaded);
                }
            }

            if (allUploads.Count == 0)
                throw new Exception("No images could be downloaded or uploaded.");

            return new CallToolResult()
            {
                Content =
                [
                    .. allUploads,
                    doc.ToJsonContent(BASE_URL)
                ]
            };
        });

    [Description("Please fill in the Google Imagen Ultra image request details.")]
    public class AIMLNewImagenUltra
    {
        [JsonPropertyName("prompt")]
        [Required]
        [Description("The text prompt describing the image.")]
        public string Prompt { get; set; } = default!;

        [JsonPropertyName("num_images")]
        [Range(1, 4)]
        [Description("Number of images to generate.")]
        public int NumImages { get; set; } = 1;

        [JsonPropertyName("aspect_ratio")]
        [Description("The aspect ratio of the image (1:1, 9:16, 16:9, 3:4, 4:3).")]
        public string AspectRatio { get; set; } = "1:1";

        [JsonPropertyName("enhance_prompt")]
        [Description("Use LLM-enhanced prompt rewriting.")]
        public bool EnhancePrompt { get; set; } = true;

        [JsonPropertyName("person_generation")]
        [Description("Allow people generation (allow_adult, dont_allow).")]
        public string PersonGeneration { get; set; } = "allow_adult";

        [JsonPropertyName("safety_setting")]
        [Description("Safety filter level (block_low_and_above, block_medium_and_above, block_only_high).")]
        public string SafetySetting { get; set; } = "block_medium_and_above";

        [JsonPropertyName("add_watermark")]
        [Description("Add invisible watermark.")]
        public bool AddWatermark { get; set; } = false;

        [JsonPropertyName("seed")]
        [Description("Random seed (use 0 for random).")]
        public uint? Seed { get; set; }

        [JsonPropertyName("filename")]
        [Required]
        [Description("The output image file name.")]
        public string Filename { get; set; } = default!;
    }

    [Description("Generate an image using AI/ML AI Gemini 2.5 Flash (aka Nano Banana) image model.")]
    [McpServerTool(Title = "Generate image with AI/ML Gemini 2.5 Flash",
           Name = "aiml_images_gemini_flash_create", Destructive = false)]
    public static async Task<CallToolResult?> AIMLImages_GeminiFlashCreate(
        [Description("Prompt for the image generation."), MaxLength(4000)] string prompt,
        IServiceProvider serviceProvider,
        RequestContext<CallToolRequestParams> requestContext,
        [Description("Number of images to generate (1-4)."), Range(1, 4)] int numImages = 1,
        [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
        CancellationToken cancellationToken = default) =>
          await requestContext.WithExceptionCheck(async () =>
       {
           var settings = serviceProvider.GetRequiredService<AIMLSettings>();
           var downloadService = serviceProvider.GetRequiredService<DownloadService>();

           // Step 1: Ask user for additional image parameters
           var (typed, notAccepted, _) = await requestContext.Server.TryElicit(
               new AIMLNewGeminiFlashImage
               {
                   Prompt = prompt,
                   Filename = filename?.ToOutputFileName() ?? requestContext.ToOutputFileName("png"),
                   NumImages = numImages,
               },
               cancellationToken);

           // Step 2: Build JSON payload
           var body = new
           {
               prompt = typed.Prompt,
               model = "google/gemini-2.5-flash-image",
               num_images = typed.NumImages
           };

           var aiml = serviceProvider.GetRequiredService<AIMLClient>();
           var doc = await aiml.PostAsync(BASE_URL, body, cancellationToken);
           var dataArray = doc.RootElement.GetProperty("data");

           if (dataArray.GetArrayLength() == 0)
               throw new Exception("No image data returned from AI/ML API.");

           var allUploads = new List<ContentBlock>();

           foreach (var item in dataArray.EnumerateArray())
           {
               var url = item.GetProperty("url").GetString();
               if (string.IsNullOrWhiteSpace(url))
                   continue;

               // Download
               var filesData = await downloadService.DownloadContentAsync(
                   serviceProvider, requestContext.Server, url, cancellationToken);

               foreach (var file in filesData)
               {
                   var safeName = $"{Path.GetFileNameWithoutExtension(typed.Filename)}_{Guid.NewGuid():N}.png";
                   var uploaded = await requestContext.Server.Upload(
                       serviceProvider, safeName, file.Contents, cancellationToken);

                   if (uploaded != null)
                   {
                       allUploads.Add(uploaded);
                   }
               }
           }

           if (allUploads.Count == 0)
               throw new Exception("No images could be downloaded or uploaded.");

           return new CallToolResult()
           {
               Content =
               [
                   .. allUploads,
                    doc.ToJsonContent(BASE_URL)
               ]
           };
       });


    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum GoogleFlashImageEditAspectRatio
    {
        [EnumMember(Value = "21:9")]
        TwentyOneNine,

        [EnumMember(Value = "1:1")]
        OneOne,

        [EnumMember(Value = "4:3")]
        FourThree,

        [EnumMember(Value = "3:2")]
        ThreeTwo,

        [EnumMember(Value = "2:3")]
        TwoThree,

        [EnumMember(Value = "5:4")]
        FiveFour,

        [EnumMember(Value = "4:5")]
        FourFive,

        [EnumMember(Value = "3:4")]
        ThreeFour,

        [EnumMember(Value = "16:9")]
        SixteenNine,

        [EnumMember(Value = "9:16")]
        NineSixteen
    }

    [Description("Generate an image edit using AI/ML AI Gemini 2.5 Flash (aka Nano Banana) image model.")]
    [McpServerTool(Title = "Generate image edit with AI/ML Gemini 2.5 Flash",
              Name = "aiml_images_gemini_flash_edit", Destructive = false)]
    public static async Task<CallToolResult?> AIMLImages_GeminiFlashEdit(
            [Description("Prompt for the image generation."), MaxLength(4000)] string prompt,
            [Description("Input file URLs. Protected SharePoint and/or OneDrive links are supported")] IEnumerable<string> imageUrls,
            IServiceProvider serviceProvider,
            RequestContext<CallToolRequestParams> requestContext,
            [Description("Number of images to generate (1-4)."), Range(1, 4)] int numImages = 1,
            [Description("Output filename without extension. Defaults to autogenerated name.")] string? filename = null,
            [Description("Ratio")] GoogleFlashImageEditAspectRatio? ratio = null,
             CancellationToken cancellationToken = default)
             => await requestContext.WithExceptionCheck(async () =>
          {
              var settings = serviceProvider.GetRequiredService<AIMLSettings>();
              var downloadService = serviceProvider.GetRequiredService<DownloadService>();

              var attachedLinks = new List<FileItem>();
              foreach (var imagUrl in imageUrls)
              {
                  var data = await downloadService.DownloadContentAsync(serviceProvider, requestContext.Server, imagUrl, cancellationToken);
                  attachedLinks.AddRange(data);
              }

              if (attachedLinks.Count > 0)
              {
                  await requestContext.Server.SendMessageNotificationAsync(
                      $"Attached {attachedLinks.Count} file(s) for image edit.", LoggingLevel.Info, cancellationToken);
              }

              // Step 1: Ask user for additional image parameters
              var (typed, notAccepted, _) = await requestContext.Server.TryElicit(
                  new AIMLNewGeminiFlashImageEdit
                  {
                      Prompt = prompt,
                      AspectRatio = ratio ?? GoogleFlashImageEditAspectRatio.OneOne,
                      Filename = filename?.ToOutputFileName() ?? requestContext.ToOutputFileName("png"),
                      NumImages = numImages,
                  },
                  cancellationToken);

              var body = new
              {
                  prompt = typed.Prompt,
                  model = "google/gemini-2.5-flash-image-edit",
                  num_images = typed.NumImages,
                  aspect_ratio = typed.AspectRatio.GetEnumMemberValue(),
                  image_urls = attachedLinks.Select(a => a.ToDataUri())
              };

              var aiml = serviceProvider.GetRequiredService<AIMLClient>();
              var doc = await aiml.PostAsync(BASE_URL, body, cancellationToken);
              var dataArray = doc.RootElement.GetProperty("data");

              if (dataArray.GetArrayLength() == 0)
                  throw new Exception("No image data returned from AI/ML API.");

              var allUploads = new List<ContentBlock>();

              foreach (var item in dataArray.EnumerateArray())
              {
                  var url = item.GetProperty("url").GetString();
                  if (string.IsNullOrWhiteSpace(url))
                      continue;

                  // Download
                  var filesData = await downloadService.DownloadContentAsync(
                      serviceProvider, requestContext.Server, url, cancellationToken);

                  foreach (var file in filesData)
                  {
                      var safeName = $"{Path.GetFileNameWithoutExtension(typed.Filename)}_{Guid.NewGuid():N}.png";
                      var uploaded = await requestContext.Server.Upload(
                          serviceProvider, safeName, file.Contents, cancellationToken);

                      if (uploaded != null)
                      {
                          allUploads.Add(uploaded);
                      }
                  }
              }

              if (allUploads.Count == 0)
                  throw new Exception("No images could be downloaded or uploaded.");

              return new CallToolResult()
              {
                  Content =
                  [
                      .. allUploads,
                    doc.ToJsonContent(BASE_URL),
                  ]
              };
          });

    [Description("Please fill in the AI image request details.")]
    public class AIMLNewGeminiFlashImage
    {
        [JsonPropertyName("prompt")]
        [Required]
        [Description("The image prompt.")]
        public string Prompt { get; set; } = default!;

        [JsonPropertyName("num_images")]
        [Range(1, 4)]
        [Required]
        [Description("Number of images to generate.")]
        public int NumImages { get; set; } = 1;

        [JsonPropertyName("filename")]
        [Required]
        [Description("The new image file name.")]
        public string Filename { get; set; } = default!;
    }


    [Description("Please fill in the AI image request details.")]
    public class AIMLNewGeminiFlashImageEdit
    {
        [JsonPropertyName("prompt")]
        [Required]
        [Description("The image prompt.")]
        public string Prompt { get; set; } = default!;

        [JsonPropertyName("num_images")]
        [Range(1, 4)]
        [Required]
        [Description("Number of images to generate.")]
        public int NumImages { get; set; } = 1;

        [JsonPropertyName("aspect_ratio")]
        [Required]
        [Description("Aspect ratio.")]
        public GoogleFlashImageEditAspectRatio AspectRatio { get; set; } = GoogleFlashImageEditAspectRatio.OneOne;

        [JsonPropertyName("filename")]
        [Required]
        [Description("The new image file name.")]
        public string Filename { get; set; } = default!;
    }
}

